### ISSUE TITLE
Filters - Cyrillic search not working

### ISSUE THREAD

**Issue by recived** [DSpace/DSpace#8914] opened 2023-06-23 12:28 UTC
demopage

https://demo7.dspace.org/search?query=%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F%20%D0%B3%D1%80%D0%B0%D0%BC%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C

item => https://demo7.dspace.org/entities/publication/1a1974ca-84ff-4016-b096-566923a47c22
filter.author = Иванов
query => https://api7.dspace.org/server/api/discover/facets/author?prefix=%D0%B8%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2&page=0&size=5&query=%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F%20%D0%B3%D1%80%D0%B0%D0%BC%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C

![image](https://github.com/DSpace/DSpace/assets/29452010/ef099fea-657b-4e46-b623-efee3328863b)

**Comment by toniprieto** [comment] 2023-07-10 11:51
Investigating this issue I have seen that the problem is the use of a regular expression pattern that does not work by default with some Unicode characters. 

https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/indexobject/ItemIndexFactoryImpl.java#L848

Adding a flag `Pattern.UNICODE_CHARACTER_CLASS` could solve the issue:

`Pattern pattern = Pattern.compile("\\b\\w+\\b", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CHARACTER_CLASS);`

**Comment by recived** [comment] 2023-07-13 16:24
> @toniprieto : Could you submit a PR with that change? It sounds like that may have solved the issue that @recived was seeing? If that's the solution, it'd be good to add this into out-of-the-box DSpace.

I checked the problem is solved.

**Comment by tdonohue** [comment] 2023-07-13 18:44
@recived : What solved the problem for you?  Was it fixed in a recent release of DSpace 7?

**Comment by toniprieto** [comment] 2023-07-13 20:07
@tdonohue I assume @recived means the change solves the issue. I have just submitted the PR, if it has been resolved in another way, it can be closed

**Comment by tdonohue** [comment] 2023-07-14 20:23
I was able to reproduce this on `main`.  It's definitely still a bug & it exists in 7.6.

To reproduce:
1. Add an author with Cyrillic characters to an existing Item:  E.g. `Иванов Иван Иванови`
2. Search for that Item.  In the "Author" filter section, use the "Search author name" box and enter in `Иванов`.  This should find that author, but it will not (this is the bug).

Verified that #8953 fixes the issue.

**Closed** 2023-07-14 20:25 UTC
Labels: bug, needs triage

**Comment by tdonohue** [comment] 2023-07-14 20:48
Ported to 7.x for 7.6.1 in #8958
