### ISSUE TITLE
Index items with tilted relationships

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#10074] opened 2024-12-04 20:43 UTC
In DSpace 7 beta 5  a new concept was added for entities: tilted relationships  https://github.com/DSpace/DSpace/pull/3134

This concept was implemented to address a performance issue for item with many relationships,. Thought it greatly Improves performance, it also creates a problem as content is not index anymore.As a results some content is not displayed anymore in the UI, and facets are also impacted.

For example: if the relation between an author and its publications is designated as Tilted, on the author page, the publications will not displayed. In the author facet, the name of the author will not be displayed anymore.

**Comment by tdonohue** [comment] 2024-12-04 23:16
@benbosman : Do you happen to know if this is a known issue with tilted relationships?  Or is there maybe a configuration missing here?  This behavior seems odd to me, as I *thought* that tilted relationships shouldn't impact the UI display.

(This tilted relationships feature is not well documented, so I'm not sure of the expected behavior in this case.)

**Comment by pilasou** [comment] 2024-12-05 14:13
Hi @tdonohue hi @benbosman, we would gladly surprise if it was just a configuration missing. We have inverstigated a lot on the relationship performance issue. The tilted option really make the job and we have found a way to display information in the UI again. It is patch that we can contribute back but before making a PR, we would like to validate our approach. The patch only involves a few files and has few line of code.

**Comment by tdonohue** [comment] 2024-12-05 14:44
@pilasou ; if you already have a patch, please go ahead and submit a PR and link to this ticket.  If you've found that fixing code corrects the behavior, then that makes it more likely to be a *bug*.   I had *thought* tilted relationships were working properly in the UI, but it's possible that the behavior broke somewhere along the way (and I haven't had a chance to re-test it myself yet).

**Comment by FelixNicol** [comment] 2024-12-05 15:19
Hi,

It is not that is is broken. When a tilted relationship is set, it will impact solr indexation as the RelationshipMetadataServiceImpl's findLatestForDiscoveryMetadataValues method is used by both the indexation and the discover search processes. The main impact of not indexing the tilted relationship is the lost of the corresponding facets indexation. 

The solution I found was to inform the item service's getMetadata if we are in the indexation process.

I added two new tilted values for indexed tilted relationships so not to impact existing relationships :
`public enum Tilted { NONE, LEFT, RIGHT, INDEXED_LEFT, INDEXED_RIGHT; }`

Made the dao (RelationshipDAOImpl.java) compatible with both. Ex:
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/77f44daf-d574-4203-9fe9-26c5af240911">

Added new signatures for ItemService, ItemServiceImpl, RelationshipMetadataService with a new parameter to tell if we are indexing. Ex:
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/a59a76d8-708b-40d0-b6d4-b6f893a2ab2d">

Here's the call from the indexation process:
<img width="1253" alt="image" src="https://github.com/user-attachments/assets/74b41e4b-3950-45e2-a3a8-f71b4850b3f5">

And added some logic to RelationshipMetadataServiceImpl to ignore tilted while indexing. Ex:
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/643a09f5-01de-4398-990b-269544bc14bc">

And an example of the new tilted values:
<img width="558" alt="image" src="https://github.com/user-attachments/assets/0d99761d-282a-405f-8bfc-775e94678c36">

If you like this approach I can send the detail as a pull request.

Thanks,
Felix Jolin-Nicol

**Comment by FelixNicol** [comment] 2024-12-05 16:34
@tdonohue I did it this way (INDEXED_LEFT and INDEXED_RIGHT) in order to prevent affecting the existing behavior. If you think it is a bug, I can use the same approach on the existing LEFT and RIGHT relationships instead. My PR would be even smaller.

**Comment by tdonohue** [comment] 2024-12-05 16:36
@FelixNicol : Yes, I think this is a bug.  I don't believe this is the intended behavior of tilted relationships.  So, if you wanted to create a smaller PR which uses the same approach for the existing `LEFT` and `RIGHT` relationships, then I'd welcome it.

**Comment by FelixNicol** [comment] 2024-12-05 16:37
Ok I will do that next week and watch for Atmire's comments to. Thank you!

**Comment by benbosman** [comment] 2024-12-06 09:51
Hi @tdonohue @FelixNicol 
I've added documentation about this functionality in https://wiki.lyrasis.org/display/DSDOC7x/Configurable+Entities#ConfigurableEntities-Tiltedrelationships

Hopefully this helps understand the functionality in more detail

**Comment by autavares-dev** [comment] 2024-12-06 19:21
I have activated the tilted relationships as suggested by @pilasou and @FelixNicol in my issue #10078. Performance has improved, and related-entities search still works (after running *index-discover -b*). DSpace version is 7.6.2.

For instance, in the Person page we have the following, with the last two being new custom relationships.
```js
<ds-tabbed-related-entities-search
      [item]="object"
      [relationTypes]="[
        {
          label: 'isAuthorOfPublication',
          filter: 'isAuthorOfPublication',
          configuration: 'default-relationships'
        },
        {
          label: 'isAdvisorOfPublication',
          filter: 'isAdvisorOfPublication',
          configuration: 'default-relationships'
        },
        {
          label: 'isCoadvisorOfPublication',
          filter: 'isCoadvisorOfPublication',
          configuration: 'default-relationships'
        },
      ]"
>
</ds-tabbed-related-entities-search>
```

**Comment by FelixNicol** [comment] 2024-12-09 19:41
I tried to reproduce the issue today, but everything looks fine. Maybe there was no bug and I did a bad manipulation. Sorry about that.

**Comment by tdonohue** [comment] 2024-12-10 15:25
Thanks for re-verifying @FelixNicol .  As you are no longer able to reproduce it, I'm closing this ticket.  If we notice the issue again we can always reopen as necessary.

**Comment by pilasou** [comment] 2024-12-10 15:26
HI @tdonohue @autavares-dev, as @FelixNicol mentionned, we tried to reproduce the indexing problem we encountered but were not able to. When the tilted property is applied to a relationship, contents and facet remains in the UI. This issue can be closed. Thanks!

**Closed by tdonohue** 2024-12-10 15:25 UTC
Labels: bug, component: Discovery, component: configurable entities, performance / caching, help wanted
