### ISSUE TITLE
Migrating the database generated by Flyway.

### ISSUE THREAD

**Issue by leandroecomp** [DSpace/DSpace#9108] opened 2023-10-04 14:12 UTC
Hi 
**Describe the bug**
I'm trying to migrate DSpace from 6.3 to 7.6. I had no problems migrating the database to version 7.5. However, when trying to update the old database to 7.6, the following problem described below occurred:

**To Reproduce**

This is the info database info before trying upgrade
```
[root ~]# /dspace/dspace-backend/bin/dspace database info
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
| Category  | Version        | Description                                                      | Type     | Installed On        | State    |
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
|           | 1              | << Flyway Init >>                                                | BASELINE | 2015-01-28 16:44:21 | Baseline |
| Versioned | 1.1            | Initial DSpace 1.1 database schema                               | SQL      | 2015-01-28 16:44:22 | Success  |
| Versioned | 1.2            | Upgrade to DSpace 1.2 schema                                     | SQL      | 2015-01-28 16:44:22 | Success  |
| Versioned | 1.3            | Upgrade to DSpace 1.3 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.3.9          | Drop constraint for DSpace 1 4 schema                            | JDBC     | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.4            | Upgrade to DSpace 1.4 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.5            | Upgrade to DSpace 1.5 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.5.9          | Drop constraint for DSpace 1 6 schema                            | JDBC     | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.6            | Upgrade to DSpace 1.6 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.7            | Upgrade to DSpace 1.7 schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 1.8            | Upgrade to DSpace 1.8 schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 3.0            | Upgrade to DSpace 3.x schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 4.0            | Upgrade to DSpace 4.x schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.08.08 | DS-1945 Helpdesk Request a Copy                                  | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.09.25 | DS 1582 Metadata For All Objects drop constraint                 | JDBC     | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.09.26 | DS-1582 Metadata For All Objects                                 | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.6.2016.08.23 | DS-3097                                                          | SQL      | 2020-12-11 10:52:36 | Success  |
| Versioned | 5.7.2017.04.11 | DS-3563 Index metadatavalue resource type id column              | SQL      | 2020-12-11 10:52:37 | Success  |
| Versioned | 5.7.2017.05.05 | DS 3431 Add Policies for BasicWorkflow                           | JDBC     | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.03.06 | DS 2701 Dso Uuid Migration                                       | JDBC     | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.03.07 | DS-2701 Hibernate migration                                      | SQL      | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.08.31 | DS 2701 Hibernate Workflow Migration                             | JDBC     | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.01.03 | DS-3024                                                          | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.01.26 | DS 2188 Remove DBMS Browse Tables                                | JDBC     | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.02.25 | DS-3004-slow-searching-as-admin                                  | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.01 | DS-1955 Increase embargo reason                                  | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.04 | DS-3086-OAI-Performance-fix                                      | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.14 | DS-3125-fix-bundle-bitstream-delete-rights                       | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.05.10 | DS-3168-fix-requestitem item id column                           | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.07.21 | DS-2775                                                          | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.07.26 | DS-3277 fix handle assignment                                    | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.08.23 | DS-3097                                                          | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.1.2017.01.03 | DS 3431 Add Policies for BasicWorkflow                           | JDBC     | 2020-12-11 10:53:02 | Success  |
| Versioned | 4.9.2015.10.26 | DS-2818 registry update                                          | SQL      |                     | Ignored  |
| Versioned | 5.0.2014.11.04 | Enable XMLWorkflow Migration                                     | JDBC     |                     | Ignored  |
| Versioned | 6.0.2015.09.01 | DS 2701 Enable XMLWorkflow Migration                             | JDBC     |                     | Ignored  |
| Versioned | 7.0.2017.10.12 | DS-3542-stateless-sessions                                       | SQL      |                     | Pending  |
| Versioned | 7.0.2018.04.03 | Upgrade Workflow Policy                                          | JDBC     |                     | Pending  |
| Versioned | 7.0.2018.04.16 | dspace-entities                                                  | SQL      |                     | Pending  |
| Versioned | 7.0.2018.06.07 | DS-3851-permission                                               | SQL      |                     | Pending  |
| Versioned | 7.0.2019.05.02 | DS-4239-workflow-xml-migration                                   | SQL      |                     | Pending  |
| Versioned | 7.0.2019.06.14 | scripts-and-process                                              | SQL      |                     | Pending  |
| Versioned | 7.0.2019.07.31 | Retrieval of name variant                                        | SQL      |                     | Pending  |
| Versioned | 7.0.2019.11.13 | relationship type copy left right                                | SQL      |                     | Pending  |
| Versioned | 7.0.2020.01.08 | DS-626-statistics-tracker                                        | SQL      |                     | Pending  |
| Versioned | 7.0.2020.10.31 | CollectionCommunity Metadata Handle                              | JDBC     |                     | Pending  |
| Versioned | 7.0.2021.01.22 | Remove basic workflow                                            | SQL      |                     | Pending  |
| Versioned | 7.0.2021.02.08 | tilted rels                                                      | SQL      |                     | Pending  |
| Versioned | 7.0.2021.03.18 | Move entity type to dspace schema                                | SQL      |                     | Pending  |
| Versioned | 7.0.2021.09.24 | Move entity type from item template to collection                | SQL      |                     | Pending  |
| Versioned | 7.0.2021.10.04 | alter collection table drop workflow stem columns                | SQL      |                     | Pending  |
| Versioned | 7.1.2021.10.18 | Fix MDV place after migrating from DSpace 5                      | SQL      |                     | Pending  |
| Versioned | 7.3.2022.04.29 | orcid queue and history                                          | SQL      |                     | Pending  |
| Versioned | 7.3.2022.05.16 | Orcid token table                                                | SQL      |                     | Pending  |
| Versioned | 7.3.2022.06.16 | process to group                                                 | SQL      |                     | Pending  |
| Versioned | 7.3.2022.06.20 | add last version status column to relationship table             | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.01 | add table subscriptionparamter change columns subscription table | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.06 | index action resource policy                                     | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.09 | Supervision Orders table                                         | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.15 | system wide alerts                                               | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.17 | Remove unused sequence                                           | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.24 | Update PNG in bitstream format registry                          | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.29 | orcid queue and history descriptions to text type                | SQL      |                     | Pending  |
| Versioned | 7.6.2023.04.19 | process parameters to text type                                  | SQL      |                     | Pending  |
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
```
Running database upgrade generates the following error
```
[root ~]# /dspace/dspace-backend/bin/dspace database migrate ignore

Database URL: jdbc:postgresql://eufrates3:5432/dspace76
You've specified to migrate your database ONLY to version ignore ...

WARNING: In this mode, we DISABLE all callbacks, which means that you will need to manually update registries and manually run a reindex. This is because you are attempting to use an OLD version (ignore) Database with a newer DSpace API. NEVER do this in a PRODUCTION scenario. The resulting database is only useful for migration testing.

Are you SURE you only want to migrate your database to version ignore? [y/n]: y
Migrating database ONLY to version ignore ... (Check logs for details)
Migration exception:
java.sql.SQLException: Flyway migration error occurred
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:838)
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:725)
        at org.dspace.storage.rdbms.DatabaseUtils.main(DatabaseUtils.java:236)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
Caused by: org.flywaydb.core.api.FlywayException: Version may only contain 0..9 and . (dot). Invalid version: ignore
        at org.flywaydb.core.api.MigrationVersion.toBigInteger(MigrationVersion.java:271)
        at org.flywaydb.core.api.MigrationVersion.tokenize(MigrationVersion.java:254)
        at org.flywaydb.core.api.MigrationVersion.<init>(MigrationVersion.java:86)
        at org.flywaydb.core.api.MigrationVersion.fromVersion(MigrationVersion.java:75)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setTargetAsString(ClassicConfiguration.java:697)
        at org.flywaydb.core.api.configuration.FluentConfiguration.target(FluentConfiguration.java:490)
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:773)
        ... 9 more
```

If running upgrade without `ignore` parameter we can see that only 4 fixes are applied:

```
[root ~]# /dspace/dspace-backend/bin/dspace database info
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
| Category  | Version        | Description                                                      | Type     | Installed On        | State    |
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
|           | 1              | << Flyway Init >>                                                | BASELINE | 2015-01-28 16:44:21 | Baseline |
| Versioned | 1.1            | Initial DSpace 1.1 database schema                               | SQL      | 2015-01-28 16:44:22 | Success  |
| Versioned | 1.2            | Upgrade to DSpace 1.2 schema                                     | SQL      | 2015-01-28 16:44:22 | Success  |
| Versioned | 1.3            | Upgrade to DSpace 1.3 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.3.9          | Drop constraint for DSpace 1 4 schema                            | JDBC     | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.4            | Upgrade to DSpace 1.4 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.5            | Upgrade to DSpace 1.5 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.5.9          | Drop constraint for DSpace 1 6 schema                            | JDBC     | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.6            | Upgrade to DSpace 1.6 schema                                     | SQL      | 2015-01-28 16:44:23 | Success  |
| Versioned | 1.7            | Upgrade to DSpace 1.7 schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 1.8            | Upgrade to DSpace 1.8 schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 3.0            | Upgrade to DSpace 3.x schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 4.0            | Upgrade to DSpace 4.x schema                                     | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.08.08 | DS-1945 Helpdesk Request a Copy                                  | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.09.25 | DS 1582 Metadata For All Objects drop constraint                 | JDBC     | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.0.2014.09.26 | DS-1582 Metadata For All Objects                                 | SQL      | 2015-01-28 16:44:24 | Success  |
| Versioned | 5.6.2016.08.23 | DS-3097                                                          | SQL      | 2020-12-11 10:52:36 | Success  |
| Versioned | 5.7.2017.04.11 | DS-3563 Index metadatavalue resource type id column              | SQL      | 2020-12-11 10:52:37 | Success  |
| Versioned | 5.7.2017.05.05 | DS 3431 Add Policies for BasicWorkflow                           | JDBC     | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.03.06 | DS 2701 Dso Uuid Migration                                       | JDBC     | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.03.07 | DS-2701 Hibernate migration                                      | SQL      | 2020-12-11 10:52:37 | Success  |
| Versioned | 6.0.2015.08.31 | DS 2701 Hibernate Workflow Migration                             | JDBC     | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.01.03 | DS-3024                                                          | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.01.26 | DS 2188 Remove DBMS Browse Tables                                | JDBC     | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.02.25 | DS-3004-slow-searching-as-admin                                  | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.01 | DS-1955 Increase embargo reason                                  | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.04 | DS-3086-OAI-Performance-fix                                      | SQL      | 2020-12-11 10:53:01 | Success  |
| Versioned | 6.0.2016.04.14 | DS-3125-fix-bundle-bitstream-delete-rights                       | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.05.10 | DS-3168-fix-requestitem item id column                           | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.07.21 | DS-2775                                                          | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.07.26 | DS-3277 fix handle assignment                                    | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.0.2016.08.23 | DS-3097                                                          | SQL      | 2020-12-11 10:53:02 | Success  |
| Versioned | 6.1.2017.01.03 | DS 3431 Add Policies for BasicWorkflow                           | JDBC     | 2020-12-11 10:53:02 | Success  |
| Versioned | 7.0.2017.10.12 | DS-3542-stateless-sessions                                       | SQL      | 2023-10-04 10:52:10 | Success  |
| Versioned | 7.0.2018.04.03 | Upgrade Workflow Policy                                          | JDBC     | 2023-10-04 10:52:10 | Success  |
| Versioned | 7.0.2018.04.16 | dspace-entities                                                  | SQL      | 2023-10-04 10:52:10 | Success  |
| Versioned | 7.0.2018.06.07 | DS-3851-permission                                               | SQL      | 2023-10-04 10:52:10 | Success  |
| Versioned | 4.9.2015.10.26 | DS-2818 registry update                                          | SQL      |                     | Ignored  |
| Versioned | 5.0.2014.11.04 | Enable XMLWorkflow Migration                                     | JDBC     |                     | Ignored  |
| Versioned | 6.0.2015.09.01 | DS 2701 Enable XMLWorkflow Migration                             | JDBC     |                     | Ignored  |
| Versioned | 7.0.2019.05.02 | DS-4239-workflow-xml-migration                                   | SQL      |                     | Pending  |
| Versioned | 7.0.2019.06.14 | scripts-and-process                                              | SQL      |                     | Pending  |
| Versioned | 7.0.2019.07.31 | Retrieval of name variant                                        | SQL      |                     | Pending  |
| Versioned | 7.0.2019.11.13 | relationship type copy left right                                | SQL      |                     | Pending  |
| Versioned | 7.0.2020.01.08 | DS-626-statistics-tracker                                        | SQL      |                     | Pending  |
| Versioned | 7.0.2020.10.31 | CollectionCommunity Metadata Handle                              | JDBC     |                     | Pending  |
| Versioned | 7.0.2021.01.22 | Remove basic workflow                                            | SQL      |                     | Pending  |
| Versioned | 7.0.2021.02.08 | tilted rels                                                      | SQL      |                     | Pending  |
| Versioned | 7.0.2021.03.18 | Move entity type to dspace schema                                | SQL      |                     | Pending  |
| Versioned | 7.0.2021.09.24 | Move entity type from item template to collection                | SQL      |                     | Pending  |
| Versioned | 7.0.2021.10.04 | alter collection table drop workflow stem columns                | SQL      |                     | Pending  |
| Versioned | 7.1.2021.10.18 | Fix MDV place after migrating from DSpace 5                      | SQL      |                     | Pending  |
| Versioned | 7.3.2022.04.29 | orcid queue and history                                          | SQL      |                     | Pending  |
| Versioned | 7.3.2022.05.16 | Orcid token table                                                | SQL      |                     | Pending  |
| Versioned | 7.3.2022.06.16 | process to group                                                 | SQL      |                     | Pending  |
| Versioned | 7.3.2022.06.20 | add last version status column to relationship table             | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.01 | add table subscriptionparamter change columns subscription table | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.06 | index action resource policy                                     | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.09 | Supervision Orders table                                         | SQL      |                     | Pending  |
| Versioned | 7.5.2022.12.15 | system wide alerts                                               | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.17 | Remove unused sequence                                           | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.24 | Update PNG in bitstream format registry                          | SQL      |                     | Pending  |
| Versioned | 7.6.2023.03.29 | orcid queue and history descriptions to text type                | SQL      |                     | Pending  |
| Versioned | 7.6.2023.04.19 | process parameters to text type                                  | SQL      |                     | Pending  |
+-----------+----------------+------------------------------------------------------------------+----------+---------------------+----------+
```
For some reason the Flyway package is generating an exception claiming that the described version of the database has a name outside the permitted standard.

**Comment by tdonohue** [comment] 2023-10-04 14:41
@leandroecomp : Your `migrate` command is incorrect.

Per the [upgrade instructions](https://wiki.lyrasis.org/display/DSDOC7x/Upgrading+DSpace), it should be:
```
# This is correct
dspace database migrate ignored
```

NOT
```
# This is INCORRECT
dspace database migrate ignore
```

Closing this as this is a support question & not a bug in DSpace itself.  If you require further support, please use one of the support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2023-10-04 14:41 UTC
Labels: bug, needs triage
