### ISSUE TITLE
Restrictions set in authentication-password.domain.valid are ignored

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8499] opened 2022-09-30 09:53 UTC
**Describe the bug**
In DSpace 7.4-Snapshot I use authentication by password, set `authentication-password.domain.valid = myuniversity.org` and expect that only users with email addresses from this domain can register an account. This was the behaviour in DSpace 6 and is described in the manual (https://wiki.lyrasis.org/display/DSDOC7x/Authentication+Plugins#AuthenticationPlugins-AuthenticationbyPassword). But this filter does not work and everyone can register, regardless their mail addresses.

Note: In the manual two versions of the parameter are listet `authentication-password.domain.valid` and `authentication-password.domain.value` but the code fetches ` authentication-password.domain.valid` in `dspace-api/src/main/java/org/dspace/authenticate/PasswordAuthentication.java` line 77.

**To Reproduce**
1. Enable Authentication by Password
2. Set `authentication-password.domain.valid = myuniversity.org` in your `local.cfg`
3. Try to register with any other domain like me@differentuniversity.org

**Expected behavior**
Only users with email addresses from myuniversity.org should be able to register an account.

**Comment by MW3000** [comment] 2022-09-30 19:53
If someone has the same problem - until it is fixed on the backend it is an easy workaround to change the validator pattern on the frontend form. Just set the pattern in `src/app/register-email-form/register-email-form.component.ts` to:

`Validators.pattern('^[a-z0-9._%+-]+@myuniversity.org$')`

**Comment by alexandrevryghem** [comment] 2023-01-19 11:59
"Atmire would like to claim this issue. It will take 2 hours to fix"

**Comment by tdonohue** [comment] 2023-01-19 17:20
@alexandrevryghem : I believe this ticket is a duplicate of #3281 , which is already claimed by Atmire & already has a bug fix PR at #8619 

Closing this as a duplicate of #3281

**Closed by tdonohue** 2023-01-19 17:20 UTC
Labels: bug, duplicate, authentication: password, good first issue, Estimate TBD, help wanted
