### ISSUE TITLE
User password reset does not work when captcha v3 is enabled! 

### ISSUE THREAD

**Issue by cdjalel** [DSpace/DSpace#8872] opened 2023-05-31 07:32 UTC
**Describe the bug**
With google reCaptcha v3 enabled in DSpace 7.5, resetting a user password yields the next UI error message:
```
Error when trying to reset password
An error occured when attempting to reset the password for the account associated with the following email address: ...
``` 
DSpace log contain:
````
2023-05-31 08:12:37,868 INFO  6d61a2c5-cc4b-47ab-98fc-3ba6fdf21fff 79b55ac9-6869-42a3-9a23-43009e2aa659 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [POST /server/api/eperson/registrations] originated from /access-control/epeople
2023-05-31 08:12:37,870 WARN  6d61a2c5-cc4b-47ab-98fc-3ba6fdf21fff 79b55ac9-6869-42a3-9a23-43009e2aa659 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Invalid captcha token (status:403 exception: Response contains invalid characters at: org.dspace.app.rest.repository.RegistrationRestRepository.createAndReturn(RegistrationRestRepository.java:104))
````

After disabling Captcha, password resetting works fine.
Untested with other versions of Captcha.

**To Reproduce**
1. Configure Google reCaptcha v3 as documented in the manual. 
2. Add new user from Access Control -> People -> Add EPerson. Then  finish user registration.
3. Reset user password from  Access Control -> People -> Edit user -> reset password.

**Expected behavior**
Pressing  'Reset password' should return a UI confirmation message and send email to the user to reset the password.

**Comment by tdonohue** [comment] 2023-07-05 20:59
Closing, appears to be a duplicate of https://github.com/DSpace/DSpace/issues/8765 which was fixed in 7.6 by https://github.com/DSpace/DSpace/pull/8766.

To fix locally, upgrade to 7.6 or apply the fixes in that PR.

**Closed by tdonohue** 2023-07-05 20:59 UTC
Labels: bug, needs triage
