### ISSUE TITLE
The pagination information is not reset when a different search query is used in the discovery page

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/DSpace#8763] opened 2023-04-05 12:00 UTC
**Describe the bug**
When a query was previously done, and a user goes through pagination in combination with actually changing the query, this can lead to no results being shown since the pagination attributes are kept

**To Reproduce**
* Do a search on DSpace 7 repository, for example: https://demo7.dspace.org/search?query=Test
* Navigate to a random pagination (For example the last one)
* Change the search query to something else with less results (make sure there are actual results, by doing the search in a separate page first), for example 'Test other'
* There are 0 results shown (Since the pagination attribute is not reset) 
    * https://demo7.dspace.org/search?query=Test%20other
    * https://demo7.dspace.org/search?query=Test%20other&spc.page=5 

**Expected behavior**
When the search query changes, there is no reason to keep any of the pagination information, since

**Comment by tdonohue** [comment] 2023-04-05 14:56
@jonas-atmire : I think this might be a duplicate of https://github.com/DSpace/dspace-angular/issues/2159 submitted by @ybnd 

So, I'm flagging this as a duplicate for now... but will wait for verification before I close it.

**Comment by tdonohue** [comment] 2023-05-15 15:26
Closing, verified this is a duplicate of https://github.com/DSpace/dspace-angular/issues/2159

**Closed by tdonohue** 2023-05-15 15:26 UTC
Labels: bug, duplicate
