### ISSUE TITLE
Restriction of email domains for self-registration has no effect

### ISSUE THREAD

**Issue by mgrothe-gu** [DSpace/DSpace#3281] opened 2021-05-26 11:44 UTC
**Describe the bug**
Setting "authentication-password.domain.valid = example.com" in the local.cfg file has no effect. Self-registration is still possible with other email domains.

**Expected behavior**
When "authentication-password.domain.valid" is specified in local.cfg, self-registration should only be possible with the respective domains.

Related to #3272

**Comment by mwoodiupui** [comment] 2021-05-26 13:31
Noted in passing:  the cause of the reported behavior is not immediately obvious to me, but it *is* immediately obvious that the test will match *too many* addresses.  In o.d.authenticate.PasswordAuthentication, each value of authentication-password.domain.valid is compared to the user's address using `String.endsWith`, so "example.com" will match "darth.vader@evil-example.com".

**Comment by tdonohue** [comment] 2021-05-26 14:26
Thanks for the analysis @mwoodiupui .  I agree, that looking at the code it seems there is a likely bug in `canSelfRegister()`: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/authenticate/PasswordAuthentication.java#L68

All that said, I'm moving this to 7.1 for now, as it seems like this code is unchanged in 7.x, so this same issue likely exists in 6.x as well.  I do think it should be fixed, but it's low priority at this time.  (That said, if someone is willing to chip in here, we can always review a PR and get it merged earlier than expected)

**Comment by pongtawat** [comment] 2021-11-29 10:53
I encounter the same problem. "authentication-password.domain.valid" doesn't work at all in DSpace 7 (tested with 7.0, but I think it's the same for 7.1). You can set it to "@example.com" but you can still register with "someone@gmail.com".

From a simple grep, it seems the registration process of DSpace 7 does not call the method "canSelfRegister" at all.

As for the behavior of canSelfRegister, I think the "endsWith" behavior is to be expected according to the comment in the code and in the config file. From the comment, we are suppose to set "authentication-password.domain.valid" to "@example.com" to limit to registration from example.com domain. However, the commented config line give an incorrect example (https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/authentication-password.cfg#L12).

**Closed** 2023-02-08 16:56 UTC
Labels: bug, high priority, authentication: password, authentication: EPerson, Estimate TBD, help wanted
