### ISSUE TITLE
When impersonating a user that can download a bitstream 

### ISSUE THREAD

**Issue by Sondissimo** [DSpace/DSpace#9028] opened 2023-08-21 17:02 UTC
**Describe the bug**
When we impersonate a user that CAN download a restricted bitstream, when trying to download it opens an error page with a 401, Unauthorized
![image](https://github.com/DSpace/DSpace/assets/119754561/f164bee5-53e8-407d-9523-86d0ffcc5660)

**To Reproduce**
Create a new item, add a bitstream and set restrictions on it, try to download when impersonating a user that is able to downlad it when logged normally

**Expected behavior**
That the user being impersonated should be able to download the file, if when logged normally he is in fact able to download it

**Comment by tdonohue** [comment] 2023-08-21 17:36
This sounds like a possible duplicate of #8957  (or at least it's very closely related)

**Comment by Sondissimo** [comment] 2023-08-21 17:40
Yes, i confirm the behaviour is actually the same

**Closed** 2023-08-21 18:07 UTC
Labels: bug, duplicate, needs triage

**Comment by tdonohue** [comment] 2023-08-21 18:08
Closing as a duplicate.  I'd recommend we use #8957 as the ticket to move forward & that one is already on our 7.6.x maintenance board looking for a volunteer.
