### ISSUE TITLE
Server loses session on UI refresh (on demo site only)

### ISSUE THREAD

**Issue by Aziris** [DSpace/DSpace#2935] opened 2020-08-21 20:59 UTC
1. Log in to DSpace
2. hit F5 to refresh page
3. User session is broken/lost and another login is required

**Comment by tdonohue** [comment] 2020-08-25 14:47
I've done further testing here.  This bug seems specific to the Angular UI demo site (https://dspace7-demo.atmire.com/).  It must be a configuration issue of that demo site.  Here's what I've found:

* If I running *both* Angular UI and REST API locally this issue does **not** exist.
* If I run the Angular UI locally, but use the demo REST API, this issue does **not** exist.
* However, if I use the demo Angular UI (which uses the demo REST API), this issue **does** exist.

**Comment by tdonohue** [comment] 2020-08-26 14:22
Closing, as this was fixed on the demo site today. It was caused by a (default) configuration issue which is described in #2938

**Closed by tdonohue** 2020-08-26 14:22 UTC
Labels: bug, needs triage
