### ISSUE TITLE
Metadata Import (bulkedit) fails to detect removal of duplicate values for a field

### ISSUE THREAD

**Issue by alawvt** [DSpace/DSpace#8253] opened 2022-04-19 21:38 UTC
**Describe the bug**

In DSpace 6.3 XMLUI

If I use "Metadata Import," i.e. https://vtechworks.lib.vt.edu/admin/metadataimport, to upload a .CSV of metadata changes and those changes are only the removal of duplicate values for a field, for example, dc.subject, DSpace does not detect those changes, reporting, "no changes were detected."

Ex. if dc.subject="apple||apple||banana||banana||cherry||cherry"

and I upload a CSV with dc.subject="apple||banana||cherry"

It will report "no changes were detected."

However if there is any change in a value. then that valued will be changed and duplicates for that value are removed. But it only updates and removed duplicates for that one value.

Ex. if dc.subject="apple||apple||banana||banana||cherry||cherry"

and I upload a CSV with dc.subject="tempapple||banana||cherry"

it will yield dc.subject="tempapple||banana||banana||cherry||cherry"

It would be really great if this could be fixed to detect removal of duplicates, since we have 1000's of articles that require deduplication of subjects.

**To Reproduce**
1. Do this: create a test item with duplicate subjects, ex. dc.subject="apple||apple||banana||banana||cherry||cherry"
2. Then this: upload a CSV with dc.subject="apple||banana||cherry"

**Expected behavior**
In the example, the desired outcome is deduplication, e.g. dc.subject="apple||banana||cherry"

**Related work**
This is related to #8186.

**Comment by alanorth** [comment] 2022-11-30 07:43
Same issue I described in https://github.com/DSpace/DSpace/issues/7989, which affects DSpace 7.5-SNAPSHOT as far as I know.

---

For a non-DSpace solution, I've purged duplicate metadata from my repository using some [elaborate SQL](https://chartio.com/learn/databases/how-to-find-duplicate-values-in-a-sql-table/) and shell shenanigans.

First, export a list of all metadata that is duplicated:

```sql
\COPY (SELECT a.text_value, a.metadata_value_id, a.metadata_field_id, a.dspace_object_id 
    FROM metadatavalue a
    JOIN (
        SELECT dspace_object_id, text_value, metadata_field_id, COUNT(*) FROM metadatavalue WHERE dspace_object_id IN (SELECT uuid FROM item) AND metadata_field_id NOT IN (11, 12, 28, 136, 159) GROUP BY dspace_object_id, text_value, metadata_field_id HAVING COUNT(*) > 1
    ) b
    ON a.dspace_object_id = b.dspace_object_id
    AND a.text_value = b.text_value
    AND a.metadata_field_id = b.metadata_field_id
    ORDER BY a.text_value) TO /tmp/duplicates.txt
```

The criteria for duplicate metadata is that it has the same text value, the same metadata field id, and the same dspace object ID. This also makes sure the metadata belongs to an item (not a collection or some other object), and that the metadata is not something like an date accessioned or available, provenance, format, etc).

The resulting text file has all metadata text values. It would be naive to delete every other line of the file because the order is not guaranteed, and some items may have triplicated (or more!) metadata, so you'd need to delete two lines, etc. In the interest of time I sorted the file by the object ID and text value so that duplicates were next to each other, then used awk to print the metadata value id for every other line, and generated a SQL file with deletes:


```console
$ sort -k4,1 /tmp/duplicates.txt    | \                                                                                                 
    awk -F'\t' 'NR%2==0 {print $2}' | \                                                                                                 
    sed 's/^\(.*\)$/DELETE FROM metadatavalue WHERE metadata_value_id=\1;/' > /tmp/delete-duplicates.sql
```

Now you can run the file in PostgreSQL (with backups! start a transaction first just in case!):

```sql
dspace=# BEGIN;
BEGIN   
dspace=# \i /tmp/delete-duplicates.sql 
DELETE 1
DELETE 1
...
dspace=# COMMIT;
```

For any metadata that was duplicated, they are now gone. Any metadata that was triplicated will now be duplicated so you should run the SQL export again to check.

I'm happy with this for now because I have thousands of duplicate metadata values gone, but would prefer it we could fix this properly for CSV batch import.

**Comment by alanorth** [comment] 2023-07-07 09:18
@tdonohue you closed this because it was filed on DSpace 6.x, but it affects 7.x as well. Mind if I re-open so that we can keep it on the radar and hopefully get it fixed one day?

**Comment by tdonohue** [comment] 2023-07-07 14:55
@alanorth : I've reopened.  Could you update the description here on how to reproduce this in 7.x?  That way we don't accidentally re-close this again thinking that it's specific to the old XMLUI.

**Comment by tdonohue** [comment] 2023-07-07 14:58
@alanorth : A follow-up question... if this is the same issue as #7989 ([as you noted above](https://github.com/DSpace/DSpace/issues/8253#issuecomment-1331756418)), is there a reason to have two tickets for this issue?  Or should we move all work to #7989 instead?

**Comment by alanorth** [comment] 2023-07-08 14:47
@tdonohue Yes this is the same issue I noticed, and my issue has a clear(er) reproducer, verified on an early DSpace 7.1. I suggest we close this one in favor of #7989.

**Closed by alanorth** 2023-07-08 14:47 UTC
Labels: bug, tools: batch-editing, tools: import, help wanted
