### ISSUE TITLE
dspace create-administrator loop after yes

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/DSpace#8189] opened 2022-02-24 15:03 UTC
After there was a database issue, every access to the database did throw an error. (Was ill, and the old admin found a mistake that all files bigger than 1MB could not get uploaded, i think might have been a tomcat issue. He started to delete wrong unused files. Then the dspace installation was suddenly not working and giving all the time an error.) Not sure if there an autoupgrade of postgres happened. I decided to delete the database and make it new. After the install instructions.
However when I started dspace create-administrator It never finishes it, after the y for yes, he is in an endless loop.

Therefore I cannot Login.
Is there a postgres direct command line to create the admin for dspace?

System debain
Backend version 7.1.1*
Flyway 6.5.7
Postgres 13.5
maven 3.6.3-5
tomcat9 9.0.43-2

**To Reproduce**
1. Drop database
2. createdb --username=postgres --owner=dspace --encoding=UNICODE dspace
3. psql --username=postgres dspace -c "CREATE EXTENSION pgcrypto;"
4. psql --username=postgres dspace
5. CREATE SCHEMA extensions;
6. CREATE EXTENSION pgcrypto SCHEMA extensions;
7. GRANT USAGE ON SCHEMA extensions TO dspace;
8. SELECT set_config('search_path',current_setting('search_path') || ',extensions',false) WHERE current_setting('search_path') !~ '(^|,)extensions(,|$)';
9. ALTER DATABASE dspace SET search_path FROM CURRENT;
10. [dspace]/bin/dspace database migrate
11. [dspace]/bin/dspace create-administrator

Tried with running dspace instance and running tomcat and solr, and also with everything not running

**Expected behavior**
create Database user

**Related work**
[Issue 8083](https://github.com/DSpace/DSpace/issues/8083)

This is the tail of dspace.log

```
2022-02-24 14:31:23,743 WARN  unknown unknown org.hibernate.cfg.annotations.EntityBinder @ HHH000482: @org.hibernate.annotations.Cache used on a non-root entity: ignored for [org.dspace.content.Site]. Please see the Hibernate documentation for proper usage.
2022-02-24 14:31:23,746 WARN  unknown unknown org.hibernate.cfg.annotations.EntityBinder @ HHH000482: @org.hibernate.annotations.Cache used on a non-root entity: ignored for [org.dspace.eperson.EPerson]. Please see the Hibernate documentation for proper usage.
2022-02-24 14:31:23,749 WARN  unknown unknown org.hibernate.cfg.annotations.EntityBinder @ HHH000482: @org.hibernate.annotations.Cache used on a non-root entity: ignored for [org.dspace.eperson.Group]. Please see the Hibernate documentation for proper usage.
2022-02-24 14:31:24,242 WARN  unknown unknown org.hibernate.orm.cache @ HHH90001007: Using legacy cache name [org.hibernate.cache.spi.UpdateTimestampsCache] because configuration could not be found for cache [default-update-timestamps-region]. Update your configuration to rename cache [org.hibernate.cache.spi.UpdateTimestampsCache] to [default-update-timestamps-region].
2022-02-24 14:31:24,244 WARN  unknown unknown org.hibernate.orm.cache @ HHH90001007: Using legacy cache name [org.hibernate.cache.internal.StandardQueryCache] because configuration could not be found for cache [default-query-results-region]. Update your configuration to rename cache [org.hibernate.cache.internal.StandardQueryCache] to [default-query-results-region].
2022-02-24 14:31:24,296 INFO  unknown unknown org.hibernate.validator.internal.util.Version @ HV000001: Hibernate Validator 6.0.18.Final
2022-02-24 14:31:56,772 INFO  unknown unknown org.dspace.eperson.EPersonServiceImpl @ anonymous::create_eperson:eperson_id=7a5bed27-f3a7-41a3-9054-a2ad769dc755
2022-02-24 14:31:57,142 INFO  unknown unknown org.dspace.eperson.PasswordHash @ Initialized a random number stream using NativePRNG provided by {Signature.SHA256withDSA KeySize=2048, Alg.Alias.Signature.2.16.840.1.101.3.4.3.1=SHA224withDSA, Alg.Alias.Signature.2.16.840.1.101.3.4.3.2=SHA256withDSA, Alg.Alias.KeyPairGenerator.1.2.840.10040.4.1=DSA, Alg.Alias.AlgorithmParameterGenerator.1.2.840.10040.4.1=DSA, CertPathValidator.PKIX=sun.security.provider.certpath.PKIXCertPathValidator, Alg.Alias.KeyPairGenerator.OID.1.2.840.10040.4.1=DSA, KeyStore.JKS=sun.security.provider.JavaKeyStore$DualFormatJKS, SecureRandom.NativePRNG ThreadSafe=true, MessageDigest.SHA-256 ImplementedIn=Software, MessageDigest.SHA-512/224=sun.security.provider.SHA5$SHA512_224, MessageDigest.SHA-512/224 ImplementedIn=Software, Alg.Alias.Signature.SHA1/DSA=SHA1withDSA, CertStore.com.sun.security.IndexedCollection ImplementedIn=Software, Alg.Alias.CertificateFactory.X509=X.509, Alg.Alias.Signature.SHA-1/DSA=SHA1withDSA, Signature.SHA224withDSA=sun.security.provider.DSA$SHA224withDSA, MessageDigest.SHA3-384=sun.security.provider.SHA3$SHA384, Signature.SHA256withDSA ImplementedIn=Software, Signature.SHA1withDSA SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey, Signature.SHA224withDSA SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey, Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.2=SHA256withDSA, Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.1=SHA224withDSA, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.1=SHA-256, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.3=SHA-512, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.2=SHA-384, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.5=SHA-512/224, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.4=SHA-224, Alg.Alias.Signature.DSAWithSHA1=SHA1withDSA, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.7=SHA3-224, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.6=SHA-512/256, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.9=SHA3-384, Alg.Alias.KeyFactory.1.3.14.3.2.12=DSA, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.8=SHA3-256, Alg.Alias.Signature.RawDSA=NONEwithDSA, MessageDigest.SHA=sun.security.provider.SHA, CertPathBuilder.PKIX=sun.security.provider.certpath.SunCertPathBuilder, Signature.NONEwithDSA KeySize=1024, Provider.id version=11, AlgorithmParameters.DSA ImplementedIn=Software, MessageDigest.SHA-512/256 ImplementedIn=Software, CertificateFactory.X.509 ImplementedIn=Software, Alg.Alias.AlgorithmParameters.1.3.14.3.2.12=DSA, Provider.id info=SUN (DSA key/parameter generation; DSA signing; SHA-1, MD5 digests; SecureRandom; X.509 certificates; PKCS12, JKS & DKS keystores; PKIX CertPathValidator; PKIX CertPathBuilder; LDAP, Collection CertStores, JavaPolicy Policy; JavaLoginConfig Configuration), CertPathBuilder.PKIX ValidationAlgorithm=RFC5280, Provider.id className=sun.security.provider.Sun, MessageDigest.SHA-512 ImplementedIn=Software, MessageDigest.SHA-224=sun.security.provider.SHA2$SHA224, CertPathBuilder.PKIX ImplementedIn=Software, SecureRandom.NativePRNGNonBlocking ThreadSafe=true, MessageDigest.SHA3-256=sun.security.provider.SHA3$SHA256, AlgorithmParameterGenerator.DSA ImplementedIn=Software, Alg.Alias.MessageDigest.1.3.14.3.2.26=SHA, AlgorithmParameters.DSA=sun.security.provider.DSAParameters, SecureRandom.SHA1PRNG=sun.security.provider.SecureRandom, MessageDigest.SHA3-224 ImplementedIn=Software, Provider.id name=SUN, MessageDigest.MD2=sun.security.provider.MD2, MessageDigest.MD5=sun.security.provider.MD5, KeyFactory.DSA=sun.security.provider.DSAKeyFactory, KeyPairGenerator.DSA KeySize=2048, SecureRandom.NativePRNG=sun.security.provider.NativePRNG, SecureRandom.NativePRNGNonBlocking=sun.security.provider.NativePRNG$NonBlocking, MessageDigest.SHA-512=sun.security.provider.SHA5$SHA512, SecureRandom.DRBG ImplementedIn=Software, Signature.SHA1withDSA KeySize=1024, SecureRandom.SHA1PRNG ThreadSafe=true, Alg.Alias.AlgorithmParameterGenerator.OID.1.2.840.10040.4.1=DSA, Alg.Alias.AlgorithmParameterGenerator.1.3.14.3.2.12=DSA, MessageDigest.MD2 ImplementedIn=Software, Signature.NONEwithDSA=sun.security.provider.DSA$RawDSA, Signature.SHA224withDSA ImplementedIn=Software, Alg.Alias.Signature.DSS=SHA1withDSA, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.10=SHA3-512, Alg.Alias.Signature.1.3.14.3.2.13=SHA1withDSA, Signature.SHA1withDSA=sun.security.provider.DSA$SHA1withDSA, CertificateFactory.X.509=sun.security.provider.X509Factory, Signature.NONEwithDSA ImplementedIn=Software, KeyStore.DKS ImplementedIn=Software, KeyStore.DKS=sun.security.provider.DomainKeyStore$DKS, Alg.Alias.Signature.OID.1.2.840.10040.4.3=SHA1withDSA, Signature.SHA256withDSAinP1363Format=sun.security.provider.DSA$SHA256withDSAinP1363Format, MessageDigest.SHA3-512=sun.security.provider.SHA3$SHA512, Alg.Alias.MessageDigest.SHA-1=SHA, MessageDigest.SHA3-512 ImplementedIn=Software, MessageDigest.SHA-384 ImplementedIn=Software, KeyStore.JKS ImplementedIn=Software, Alg.Alias.Signature.DSA=SHA1withDSA, Signature.NONEwithDSA SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey, Signature.SHA224withDSA KeySize=2048, Alg.Alias.AlgorithmParameters.OID.1.2.840.10040.4.1=DSA, KeyStore.PKCS12=sun.security.pkcs12.PKCS12KeyStore$DualFormatPKCS12, Alg.Alias.Signature.SHAwithDSA=SHA1withDSA, SecureRandom.SHA1PRNG ImplementedIn=Software, MessageDigest.SHA-256=sun.security.provider.SHA2$SHA256, KeyStore.CaseExactJKS=sun.security.provider.JavaKeyStore$CaseExactJKS, Policy.JavaPolicy=sun.security.provider.PolicySpiFile, Alg.Alias.MessageDigest.SHA1=SHA, MessageDigest.SHA-224 ImplementedIn=Software, Signature.SHA1withDSAinP1363Format=sun.security.provider.DSA$SHA1withDSAinP1363Format, KeyFactory.DSA ImplementedIn=Software, SecureRandom.DRBG=sun.security.provider.DRBG, MessageDigest.SHA3-224=sun.security.provider.SHA3$SHA224, CertStore.com.sun.security.IndexedCollection=sun.security.provider.certpath.IndexedCollectionCertStore, CertStore.Collection=sun.security.provider.certpath.CollectionCertStore, Signature.SHA1withDSA ImplementedIn=Software, AlgorithmParameterGenerator.DSA KeySize=2048, Alg.Alias.Signature.SHA/DSA=SHA1withDSA, CertPathValidator.PKIX ValidationAlgorithm=RFC5280, MessageDigest.SHA-384=sun.security.provider.SHA5$SHA384, KeyStore.CaseExactJKS ImplementedIn=Software, CertPathValidator.PKIX ImplementedIn=Software, Alg.Alias.Signature.1.2.840.10040.4.3=SHA1withDSA, MessageDigest.SHA ImplementedIn=Software, MessageDigest.MD5 ImplementedIn=Software, Configuration.JavaLoginConfig=sun.security.provider.ConfigFile$Spi, KeyPairGenerator.DSA ImplementedIn=Software, Alg.Alias.KeyFactory.1.2.840.10040.4.1=DSA, MessageDigest.SHA3-384 ImplementedIn=Software, SecureRandom.NativePRNGBlocking ThreadSafe=true, Alg.Alias.Signature.1.3.14.3.2.27=SHA1withDSA, Alg.Alias.KeyPairGenerator.1.3.14.3.2.12=DSA, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.1=SHA-256, AlgorithmParameterGenerator.DSA=sun.security.provider.DSAParameterGenerator, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.3=SHA-512, SecureRandom.DRBG ThreadSafe=true, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.2=SHA-384, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.5=SHA-512/224, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.4=SHA-224, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.7=SHA3-224, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.6=SHA-512/256, MessageDigest.SHA3-256 ImplementedIn=Software, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.9=SHA3-384, Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.8=SHA3-256, Alg.Alias.AlgorithmParameters.1.2.840.10040.4.1=DSA, MessageDigest.SHA-512/256=sun.security.provider.SHA5$SHA512_256, Signature.NONEwithDSAinP1363Format=sun.security.provider.DSA$RawDSAinP1363Format, Alg.Alias.MessageDigest.OID.1.3.14.3.2.26=SHA, Signature.SHA256withDSA=sun.security.provider.DSA$SHA256withDSA, Signature.SHA224withDSAinP1363Format=sun.security.provider.DSA$SHA224withDSAinP1363Format, CertStore.Collection ImplementedIn=Software, Alg.Alias.KeyFactory.OID.1.2.840.10040.4.1=DSA, Signature.SHA256withDSA SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey, Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.10=SHA3-512, KeyPairGenerator.DSA=sun.security.provider.DSAKeyPairGenerator$Current, SecureRandom.NativePRNGBlocking=sun.security.provider.NativePRNG$Blocking}
2022-02-24 14:31:57,158 INFO  unknown unknown org.dspace.eperson.EPersonServiceImpl @ anonymous::update_eperson:eperson_id=7a5bed27-f3a7-41a3-9054-a2ad769dc755
2022-02-24 14:31:57,197 INFO  unknown unknown org.dspace.eperson.GroupServiceImpl @ anonymous::update_group:group_id=1497fe3b-a4de-41e2-b18e-517524b8c245
```

**Comment by tdonohue** [comment] 2022-02-24 18:37
@WolfgangT71 : Please check you `dspace.log` and the PostgreSQL log file for any errors that occur when you attempt to login.  Additionally, you should check if errors were reported in the `dspace.log` when you ran `./dspace database migrate`.

It sounds likely that some part of the `dspace database migrate` **failed** and reported something in the logs.  That failure could then result in `create-administrator` not working properly.  But, it's impossible to say what the fix may be without knowing what error may have occurred during the `migrate` or similar.

**Comment by WolfgangT71** [comment] 2022-02-25 07:16
postgres.log
`2022-02-25 06:35:51.125 UTC [13404] LOG:  starting PostgreSQL 13.5 (Debian 13.5-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-02-25 06:35:51.126 UTC [13404] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-02-25 06:35:51.127 UTC [13404] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-02-25 06:35:51.133 UTC [13405] LOG:  database system was shut down at 2022-02-25 06:35:33 UTC
2022-02-25 06:35:51.144 UTC [13404] LOG:  database system is ready to accept connections
2022-02-25 06:36:27.704 UTC [13521] dspace@dspace FATAL:  database "dspace" does not exist
2022-02-25 06:36:27.812 UTC [13522] dspace@dspace FATAL:  database "dspace" does not exist
2022-02-25 06:44:35.925 UTC [13571] postgres@dspace ERROR:  extension "pgcrypto" already exists
2022-02-25 06:44:35.925 UTC [13571] postgres@dspace STATEMENT:  CREATE EXTENSION pgcrypto SCHEMA extensions;
2022-02-25 06:53:30.601 UTC [13800] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-25 06:53:30.603 UTC [13799] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-25 06:54:54.490 UTC [13840] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-25 06:54:54.490 UTC [13839] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-25 07:12:44.711 UTC [16508] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-25 07:12:44.713 UTC [16507] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
`

**Comment by WolfgangT71** [comment] 2022-02-25 07:26
The dspace.log as zip.
[dspace.zip](https://github.com/DSpace/DSpace/files/8139289/dspace.zip)

Tried everything again, including a mvn package and a fresh_install. Cleaned all log files before I started again. Still the same result.

**Comment by WolfgangT71** [comment] 2022-02-25 08:50
Just to make sure did not change to backend 7.2 will try this on monday.

**Comment by tdonohue** [comment] 2022-02-25 20:54
@WolfgangT71 : Your dspace.log shows a lot of ERROR lines that say DSpace cannot connect to your Solr instance. For example:
```
2022-02-25 06:54:44,089 ERROR unknown unknown org.dspace.discovery.SolrSearchCore @ Error while initializing solr server
org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://localhost:8983/solr/search
```

DSpace requires Solr to be functional, otherwise you may see very odd behavior.

**Comment by WolfgangT71** [comment] 2022-02-27 17:29
ok, solr went down, when reinstalling the configsets, needed some permission corrections. But that was not the problem. could try to give ownership to tomcat instead of solr. But solr is now reachable from the web. Problem with create-administrator persists. Will update to 7.2. And drop database again. Will report back later.

**Comment by WolfgangT71** [comment] 2022-02-27 21:15
7.2 also not working, is it working already with Postgres 13.5?

**Comment by WolfgangT71** [comment] 2022-02-27 22:10
What are tested postgres versions, for the main branch of 7.2?

**Comment by WolfgangT71** [comment] 2022-02-27 23:29
So tried now to install postgres 12.10 and still not working.
Solr is up and running.

This came by fresh_install
`test_database:
     [java] 2022-02-27 23:28:12,419 WARN  org.dspace.servicemanager.DSpaceServiceManager @ Unable to locate bean by name or id=database. Will try to look up bean by type next.
     [java] org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'database' available
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:808) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1279) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
     [java] 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1114) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
     [java] 	at org.dspace.servicemanager.DSpaceServiceManager.getServiceByName(DSpaceServiceManager.java:426) [dspace-services-7.2.jar:7.2]
     [java] 	at org.dspace.scripts.ScriptServiceImpl.getScriptConfiguration(ScriptServiceImpl.java:33) [dspace-api-7.2.jar:7.2]
     [java] 	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:125) [dspace-api-7.2.jar:7.2]
     [java] 	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98) [dspace-api-7.2.jar:7.2]
     [java] 
     [java] Attempting to connect to database
     [java] Connected successfully!
     [java] 
     [java] Database Type: postgres
     [java] Database URL: jdbc:postgresql://localhost:5432/dspace
     [java] Database Schema: public
     [java] Database Username: dspace
     [java] Database Software: PostgreSQL version 12.10 (Debian 12.10-1.pgdg110+1)
     [java] Database Driver: PostgreSQL JDBC Driver version 42.2.25
     [java] PostgreSQL 'pgcrypto' extension installed/up-to-date? true (version=1.3)
     [java] FlywayDB Version: 6.5.7
     [java] 2022-02-27 23:28:13,087 WARN  org.dspace.services.sessions.StatelessRequestServiceImpl @ Request interceptor (org.dspace.services.events.SystemEventService$EventRequestInterceptor@5ebefaeb) failed to execute on end (request-303-1646004492448): null
`

**Comment by WolfgangT71** [comment] 2022-02-27 23:38
postgresql.log
`2022-02-27 23:18:22.807 UTC [52306] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-02-27 23:18:22.807 UTC [52306] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-02-27 23:18:22.809 UTC [52306] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-02-27 23:18:22.858 UTC [52307] LOG:  database system was shut down at 2022-02-27 23:18:22 UTC
2022-02-27 23:18:22.877 UTC [52306] LOG:  database system is ready to accept connections
2022-02-27 23:28:13.132 UTC [53220] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-27 23:28:13.133 UTC [53219] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-27 23:30:13.057 UTC [53264] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
2022-02-27 23:30:13.057 UTC [53263] dspace@dspace LOG:  could not receive data from client: Connection reset by peer
`

**Comment by WolfgangT71** [comment] 2022-02-27 23:50
dspace.log

[dspace.zip](https://github.com/DSpace/DSpace/files/8149639/dspace.zip)

**Comment by WolfgangT71** [comment] 2022-02-28 06:17
I can reach it from outside. But not from localhost.

**Comment by WolfgangT71** [comment] 2022-02-28 06:43
http://dspace.umiz.at:8983/solr/#/search/core-overview

Can reach it like this, but only as my ip Addresses are given free to reach it.

**Comment by WolfgangT71** [comment] 2022-02-28 07:56
If I start
`http://localhost:8983/solr/search/select)
`

I get when saved:
`{
  "responseHeader":{
    "status":0,
    "QTime":3,
    "params":{}},
  "response":{"numFound":0,"start":0,"numFoundExact":true,"docs":[]
  }}
`

**Comment by WolfgangT71** [comment] 2022-02-28 09:03
Newest log file, no solr errors in it.

[dspace.zip](https://github.com/DSpace/DSpace/files/8151901/dspace.zip)

**Comment by WolfgangT71** [comment] 2022-02-28 09:03
But still not working

**Comment by WolfgangT71** [comment] 2022-02-28 11:23
Just to check, I tried installing postgresql 14 with contrib, than the solr errors are reappearing again.
But also had the errors with postgresql 13.
Problem might be that in my system only 13 and 14 have contrib, v 12 does not have a matching contrib to install.

**Comment by mwoodiupui** [comment] 2022-02-28 13:26
I currently do all of my DSpace development and testing with PostgreSQL v13.5.

The WARNing "Unable to locate bean by name or id=database. Will try to look up bean by type next." is expected in this context.

The connection test appears to succeed, and seems to be giving reasonable values for the connection parameters.

The WARNing "Request interceptor (org.dspace.services.events.SystemEventService$EventRequestInterceptor@5ebefaeb) failed to execute on end (request-303-1646004492448): null " is one that I always see when installing.  I've not spent the time to find out where this interceptor is or why it is not executing, because it seems not to be a problem.

I don't see any relevant messages in the latest attached `dspace.log`.  You may have to step through the create-administrator code with a debugger to identify the problem.  (We *should* be logging something -- this is a second problem.)

**Comment by tdonohue** [comment] 2022-02-28 15:44
@WolfgangT71 : Like @mwoodiupui noted, I don't see any obvious issues based on the logs you've provided.  What you want to be looking for are any log lines that are of an `ERROR` or `FATAL` status...**especially when you attempt to run the command that isn't working for you**.  Make sure to check ALL the relevant logs (DSpace, Tomcat, Postgres, Solr, etc)...as it's possible the issue could be logged in any of those areas.

I'd highly recommend reviewing our Troubleshooting guide if you need help finding error messages in logs:
https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

Also, please keep in mind that normally we do NOT use GitHub Issues for support questions. Instead, support is available through one of the support options at https://wiki.lyrasis.org/display/DSPACE/Support  For technical support, we recommend using (and searching) our Tech Support mailing list (https://groups.google.com/d/forum/dspace-tech) -- as that ensures that others can help out if they've hit a similar issue.  It's also a good place to search if you discover an odd error message, in case someone else has already found a way to solve that problem.

As we are not able to reproduce this issue, I'm going to close this ticket as "cannot reproduce".  If you need further help, use one of our Support options listed above.  But, please first try to find more information on the underlying error (as sending us logs to comb through makes it harder to help, as we all provide support in our volunteer time).  If we later find that there's an actual bug in the codebase, we can always reopen this ticket as needed.

**Closed by tdonohue** 2022-02-28 15:44 UTC
Labels: bug, cannot reproduce, needs triage
