### ISSUE TITLE
RSS feed exposes item that is fully restricted.

### ISSUE THREAD

**Issue by blancoj** [DSpace/DSpace#9511] opened 2024-04-29 19:20 UTC
If you create an item that has restrictions on the item and files, it will still show up on the RSS feed. It should really not show  up.

**To Reproduce**
1. Create an item that has full restrictions on the item and the files.
2. Go to the collection page belonging to this item, and select the RSS feed.  The item should not show up on the feed, but it does anyway.

**Expected behavior**
An item with restrictions should not show up on the RSS feed.

**Related work**

**Comment by pilasou** [comment] 2024-05-16 14:38
Hi @blancoj @tdonohue , I tried to reproduce, but the item I restricted in DSpace sandbox is not showing when I looked at the RSS. It also desappeared from the UI if I am looking as Anonymous user. I applied the following restriction policies at the ITEM level and Bitstream level: 
![image](https://github.com/DSpace/DSpace/assets/19291880/375ff5f0-291f-41c2-80aa-48776be4d54b)

Those policies are from an item I used today (2024-06-16) in "Publications 2" Collection in DSpace Sandbox: https://sandbox.dspace.org/collections/dd1240ae-d7dd-405c-bdc3-d6c960609433 

Is it another kind of restriction that I should apply?

**Comment by tdonohue** [comment] 2024-05-16 20:09
@blancoj : I'm not able to reproduce this on https://sandbox.dspace.org (running pre-8.0) nor the https://demo.dspace.org (running pre-7.6.2).

Here's what I did:
1. Deposit a brand new item which is public (as is the default)
2. Login as an Admin, and Edit the Item.
3. On the "Access Control" tab, I selected both "Item's Metadata" and "Bitstreams" and replaced access conditions with "administrator".  (This is the same as editing all Resource/Access Policies to use "Administrator" group instead of "Anonymous")
4. Then, I went back to the Item.  Selected its parent Collection, and clicked on the RSS feed button.
5. Searched the RSS feed for the restricted Item's name or Handle.  **It is not found.**
6. I also tried accessing the Collection RSS & Sitewide RSS feed as an anonymous user.  The restricted item is still NOT found.

Here's an example from the demo site: https://demo.dspace.org/items/a1f85e6b-eca2-451c-a8d1-22828a37776c   This fully restricted Item is in this Collection: https://demo.dspace.org/collections/9d8334e9-25d3-4a67-9cea-3dffdef80144

I'm closing this issue as it doesn't seem to be reproducible.  Both @pilasou and I could not reproduce it.  If you can find a way to reproduce it reliably on the Demo or Sandbox, then we can reopen this ticket.

**Closed by tdonohue** 2024-05-16 20:09 UTC
Labels: bug, high priority, authorization, help wanted, testathon, integration: syndication feed
