### ISSUE TITLE
Search page result number bug

### ISSUE THREAD

**Issue by dsipos-dev** [DSpace/DSpace#3140] opened 2021-01-07 15:31 UTC
**Describe the bug**
When Paginating on search results there is a bug with the number of result i get. 
The result page sad "Now showing 111 - 120 of 890" so 10 item, but there are only 8 result item
![image](https://user-images.githubusercontent.com/71388767/103910404-12618780-5105-11eb-9dbc-a1f68a35a028.png)

**To Reproduce**
1. Open : https://dspace7-demo.atmire.com/search?page=12&view=gridElement&pageId=search-page-configuration&pageSize=10&sortDirection=DESC&sortField=score

**Expected behavior**
10 result element

**Comment by tdonohue** [comment] 2021-02-01 16:14
I've transferred this to DSpace/DSpace as it appears to be a backend bug (Discovery or REST API is returning the wrong number of items on a given page).  I'm able to see this behavior in the REST API directly in these two pages:

* Page size is 10, but only 9 items are returned. There is a [next page though](https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=12&size=10) which shows 10 items: https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=11&size=10
* Previous page (to one above) shows only 7 items: https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=10&size=10

You can also see this same behavior on the **first page** of results on the demo site when searching for "test":
* Page size is 10, but only 8 items are returned. There are 189 though in the result set: https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&query=test

I've not been able to determine the issue here, but it's obvious that pagination is not behaving properly here.

**Comment by tdonohue** [comment] 2021-02-02 18:30
I've been able to reproduce this problem by **deleting** Items.  So, it might be that the pagination count is somehow including deleted items.  For example, if I delete two items off the first page (of 10), then if I hard refresh and revisit that page, it now just has 8 items listed.

**Comment by tdonohue** [comment] 2021-02-11 16:58
@benbosman : Could you or someone on your team look into this odd issue & provide an estimate?  As noted above, it seems to me almost like pagination is including deleted items and the numbers sometimes get off on specific pages.

**Comment by abollini** [comment] 2021-03-05 12:03
hi @tdonohue I have investigated and I was still able to reproduce this issue on the demo repository. I have got a lot of errors initially related to a missing journal scheme (maybe it was deleted or never loaded) anyway after adding it back the log are clean and nothing wrong is reported when an item is deleted.
I have noted two different scenarios
- when I delete an item of Camerons so with a relation the item stays in the solr index with the resulting issue
- when I delete simple item (not entity, without relations) no errors occur.

Our test cover only deletion of simple item so my suggestion is to add a test to verify if the source of the issue is indeed the deletion of an Entity item (with or without) relations and use this test to investigate further.

Moreover, I have tried also to delete this item https://demo7.dspace.org/items/8dfa3d48-5d54-4239-82ed-d521300313be
that was the 3rd of this search (as admin) https://demo7.dspace.org/search?page=1&query=infection&scope=&pageId=search-page-configuration&pageSize=10&sortDirection=DESC&sortField=score

to double check my hypothesis but unfortunately I got an error 
```
2021-03-05 11:53:31,413 INFO  org.dspace.content.Item @ dspacedemo+admin@gmail.com::delete_item:item_id=8dfa3d48-5d54-4239-82ed-d521300313be
2021-03-05 11:53:31,414 INFO  org.dspace.content.RelationshipServiceImpl @ dspacedemo+admin@gmail.com::delete_relationship:relationship_id=1502&copyMetadataValuesToLeftItem=false&copyMetadataValuesToRightItem=false
2021-03-05 11:53:31,508 INFO  org.dspace.content.Item @ dspacedemo+admin@gmail.com::update_item:item_id=8dfa3d48-5d54-4239-82ed-d521300313be
2021-03-05 11:53:31,523 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.NullPointerException: null
	at org.dspace.content.dao.impl.EntityTypeDAOImpl.findByEntityType(EntityTypeDAOImpl.java:30) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.EntityTypeServiceImpl.findByEntityType(EntityTypeServiceImpl.java:32) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.RelationshipServiceImpl.findModifiedDiscoveryItemsForCurrentItem(RelationshipServiceImpl.java:453) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.RelationshipServiceImpl.updateItemsInRelationship(RelationshipServiceImpl.java:416) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.RelationshipServiceImpl.deleteRelationshipAndCopyToItem(RelationshipServiceImpl.java:380) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.RelationshipServiceImpl.forceDelete(RelationshipServiceImpl.java:366) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.ItemServiceImpl.rawDelete(ItemServiceImpl.java:688) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:669) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:69) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
	at org.dspace.app.rest.repository.ItemRestRepository.delete(ItemRestRepository.java:175) ~[classes/:7.0-beta5-SNAPSHOT]
```

this could be related to mess data or indicate an additional issue.

At the current stage I can only make a best bet for the estimation: 8-24hours
let me know if we can work further on that

**Comment by tdonohue** [comment] 2021-03-05 14:48
Thanks @abollini . I'll add an estimate of 16 hours here (middle point of your range).  I'll assign this back to you for your team to work on & let me know if it goes over that number of hours. However, if you have concerns about getting this done for Beta 5 let me know so that we can get more help or reassign as needed.

**Closed** 2021-03-12 23:05 UTC
Labels: bug, component: Discovery, e/16
