### ISSUE TITLE
Possibility for admins to push items back directly into the workflow pool

### ISSUE THREAD

**Issue by S-Eiberger** [DSpace/DSpace#8751] opened 2023-03-29 15:02 UTC
**Is your feature request related to a problem? Please describe.**
We have several editors and in some cases (in case of a longer illness etc.) it is necessary to move an item that has already been assigned to an editor back into the common workflow pool so that another editor can approve, reject or edit this item.

At the moment the admin can only return an item completely to the submitter, which requires a resubmission so that this item can be reassigned to another collaborator. This seems to me to be very laborious and not very user friendly, as it requires further actions by the submitter. 

**Describe the solution you'd like**
An adjustment to the _Administer Workflow_ submenu so that the admin also has the option to push items directly back into the shared workflow pool and not have to return them completely to the submitter. This would help a lot.

**Comment by AndrewAlesik** [comment] 2024-07-16 11:33
Hi @tdonohue , 
Is this issue connected with the PR to DSpace 8 that I made earlier?
https://github.com/DSpace/dspace-angular/pull/3054

**Comment by tdonohue** [comment] 2024-07-17 15:03
@AndrewAlesik : thanks for pointing this out.  Yes, this issue ticket looks like a duplicate of https://github.com/DSpace/dspace-angular/issues/1970   I'm going to simply close this issue as https://github.com/DSpace/dspace-angular/issues/1970 has much more activity (including your PRs).

**Closed by tdonohue** 2024-07-17 15:03 UTC
Labels: new feature, component: workflow, help wanted
