### ISSUE TITLE
 authentication error shibboleth 

### ISSUE THREAD

**Issue by cipfiz** [DSpace/DSpace#2916] opened 2020-08-04 09:34 UTC
Dspace 7 receive empty value from shibboleth:

2020-08-04 11:17:39,880 DEBUG org.dspace.authenticate.ShibAuthentication @ ShibAuthentication - attribute mail is empty!
2020-08-04 11:17:39,880 ERROR org.dspace.authenticate.ShibAuthentication @ Shibboleth authentication was not able to find a NetId, Email, or Tomcat Remote user for which to indentify a user from.
2020-08-04 11:17:39,881 DEBUG org.dspace.authenticate.ShibAuthentication @ ShibAuthentication - attribute mail is empty!
2020-08-04 11:17:39,881 DEBUG org.dspace.authenticate.ShibAuthentication @ ShibAuthentication - attribute givenName is empty!
2020-08-04 11:17:39,881 DEBUG org.dspace.authenticate.ShibAuthentication @ ShibAuthentication - attribute sn is empty!
2020-08-04 11:17:39,899 **ERROR org.dspace.authenticate.ShibAuthentication @ Unable to register new eperson because we are unable to find an email address along with first and last name for the user.**
  NetId Header: 'null'='null' (Optional) 
  Email Header: 'mail'='null' 
  First Name Header: 'givenName'='null' 
  Last Name Header: 'sn'='null'

But in the shibboleth I receive the authentication data:

2020-08-04 11:09:26|Shibboleth-TRANSACTION.Login|**test@example.com**|_37a933a02565057512061ad02ccb9e0e|https://idp3-example.com/idp/shibboleth|_5b973d9e7099c43c1bb1b6e7c3a6470c|urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport|2020-08-04T10:41:45|**mail**|AAdzZWNyZXQxs+3UzwKOW1zy7rkVEaQl9ILTZMGGa+ia7FwPUruj8fMGQhLTGDvlRHhUGkOf5HNbpwS3nQ2C8B7e5+AXFMH6gpgeI=|urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST||urn:oasis:names:tc:SAML:2.0:status:Success|||Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0|zzzzzz

In apache configuration I have:

  <Location />
 	AuthType shibboleth
 	ShibRequireSession Off
 	require shibboleth
     </Location>

     <Location "/Shibboleth.sso">
	Require all granted
 	SetHandler shib
 	</Location>	

    <Location /server/api/authn/shibboleth>
	Require all granted
        AuthType shibboleth
        ShibUseHeaders On
        ShibUseEnvironment On
        Require shibboleth
	
    </Location>

    <Location /server/api/authn/login>
	Require all granted
        AuthType shibboleth
        ShibUseHeaders On
        ShibUseEnvironment On
        Require shibboleth
	
    </Location>

    <Proxy *>
        AddDefaultCharset Off
	Require all granted
        #Order deny,allow
        #Allow from all
    </Proxy>
    SSLProxyEngine on

    ProxyIOBufferSize 65536
    ProxyRequests off
    ProxyPreserveHost On
    ProxyPass /Shibboleth.sso !

    # A specific proxypass configuration for DSpace server (both server and angular on the same machine)
    ProxyPass /server ajp://localhost:8009/server
    ProxyPassReverse /server ajp://localhost:8009/server
 
    # A specific proxypass configuration for Angular
    ProxyPass / http://localhost:4000/
    ProxyPassReverse / http://localhost:4000/

In web browser I have:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Aug 04 11:09:27 EEST 2020
There was an unexpected error (type=Unauthorized, status=401).
Login failed

**Comment by tdonohue** [comment] 2020-08-04 14:49
This was also asked on the mailing list, where I answered the question:
https://groups.google.com/g/dspace-tech/c/qRoprzbNsiE/m/m2EP0i-oAgAJ

@cipfiz : I'm going to close this ticket as it sounds (to me) like a configuration issue & not a bug.  If we find otherwise, we obviously can reopen the ticket later on.

**Closed by tdonohue** 2020-08-04 14:49 UTC
