### ISSUE TITLE
dspace create-administrator loop after yes

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/DSpace#8083] opened 2021-12-20 13:32 UTC
After upgrading some problems with not being able to upload items reappeared, so I decided to make a complete new installation, including droping the dspace database.
Than I made a complete new installation.
However when I started `dspace create-administrator` It never finishes it, after the y for yes, he is in an endless loop.

Therefore I cannot Login.
Is there a postgres direct command to create the admin for dspace?

Backend version 7.1.1

**Comment by tdonohue** [comment] 2021-12-20 15:21
@WolfgangT71 : Could you check for errors thrown in your `dspace.log`?  I suspect that an error is being thrown, as I'm not able to reproduce this locally.  Closing, as I think this is likely a configuration or setup error (check your logs).

If you need more help, then please contact us via one of the recommended Support routes: https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2021-12-20 15:21 UTC
Labels: needs triage

**Comment by WolfgangT71** [comment] 2021-12-21 10:17
Behind this was a general system problem. I think th emost problems did arise, with postgresql V13.5 and node.js vs. 14 which both are above current approved version. Changed now to debian 11,and there everything needed, so that it works correct is in the standard repositories. And so it was very easy to install, without any problems. Up and running now.
