### ISSUE TITLE
Administrative metadata fields missing when a Item was updated from OAI - Private items are public after update

### ISSUE THREAD

**Issue by Gerafp** [DSpace/DSpace#9646] opened 2024-06-12 19:33 UTC
Hi All.

Recently, we updated DSpace from version 5.4 to 7.6 in CIMMYT. Unfortunately, we've been experiencing some issues after update. The firts one it's relatedw with the OAI harvest. The librarian team deteted that some metadata fields are missing on items were harvested before. I mean, when an item is harvesting for the firts time, all data is correct, but when they made changes at the source and Dspace detects changes, it re-harvests the item. This process causes some metadata to be lost, including administrative fields created when and item is published, such as:

- dc.identifier.uri
- dc.description.provenance
- dc.date.available
- dc.date.accessioned

When the librarian team reported this, DSpace had already harvested a significant number of items, and they now need to review all of them to identify missing metadata and restore the items.

Do you have any report about this issue? In our case, it is very important to find a solution because a lot of work could be lost.

1. Harvest content using OAI
2. Make changes in the item - Source
3. Harvest content again

Another issue we detected after updating our DSpace is less critical than the first one but still important to mention. Some items were set to "private" in Dspace 5.4 apparead as "public" after the update process. We had a list of these items and we've updated their state to set "private" as before using SQL queries, but we report if someone are experiencing the same issue. 

Let me know if you have reports about these issues or if you need more information.

We are searching for ways to solve the firts issue, welcome any suggestions.

Regards,

[CIMMYT UI](https://repository.cimmyt.org/)

[CIMMYT BACK](https://repository.cimmyt.org/server)

**Comment by tdonohue** [comment] 2024-07-26 16:07
This ticketing system is not the best place to ask support questions, as it's meant for reporting discovered bugs & assigning tasks to developers.  As of today, I've not heard of these issues reported from others in the DSpace community.  However, the best place to ask would be via one of the mailing lists listed in our [support options](https://wiki.lyrasis.org/display/DSPACE/Support).

Because this is the first report of this type, it's difficult to say whether this is a bug or not.  It might be, but it also could be that some sort of error occurred that resulted in unexpected behavior.  So, you also should check for errors in logs when you are harvesting via OAI.

You also could try to reproduce this error on our demo site (https://demo.dspace.org) and list the steps you took to do so.  If it is reproducible on other sites (like demo), that's a sign this may be a bug.

For now, I'm going to close this ticket as "answered".  However, we can reopen if we get more details that lead us to think that it may be a bug.

**Closed by tdonohue** 2024-07-26 16:07 UTC
Labels: bug, needs triage
