### ISSUE TITLE
DSpace 8.0 - `dspace.dir` option does not update during deploy

### ISSUE THREAD

**Issue by parphis** [DSpace/DSpace#9689] opened 2024-07-10 10:13 UTC
## Describe the bug
DSpace 8.0, Debian 12
`dspace.dir` and `logging.config` options are not updated within the [dspace]/webapps/server/WEB-INF/classes/application.properties file during the compile and deploy process.
Even if I set the correct path of `dspace.dir` to our custom DSpace folder in [dspace-src]/local.cfg the file `application.properties` will contain `dspace.dir=dspace` which then breaks the server to start.

## To Reproduce
 1. Create a custom [cust-ds-fld] folder for your DSpace server.
 2. Change/set the option `dspace.dir` to the [cust-ds-fld] in the [dspace-src]/local.cfg file.
 3. Compile and deploy your server.
 4. Start the server - embedded or installed Tomcat instance do the same.
 5. The server will not start due to the following error in `catalina.out`:
```text
Logging system failed to initialize using configuration from '/dspace/config/log4j2.xml'
java.io.FileNotFoundException: /dspace/config/log4j2.xml (No such file or directory)
```

## Expected behavior
The `dspace.dir` option should be updated/synchronized by the one whithin the [dspace-src]/local.cfg

## Related work
n/a

**Comment by tdonohue** [comment] 2024-07-10 14:15
@parphis : I'm having difficulty reproducing this bug.  Here's what I've tried from the `dspace-8_x` branch (which is identical to 8.0 at this time):

1. Checkout `dspace-8_x`
2. Create a `local.cfg` file under `[src]/dspace/config`.  Add a custom value to `dspace.dir`, for example:
    ```
    dspace.dir = /some/custom/dspace/folder/
    ```
3. (Re)Build everything via `mvn -U clean package`
4. After build completes, check the `[src]/dspace/target/dspace-installer/webapps/server/WEB-INF/classes/application.properties` file.  Verify it has that custom setting (it does).

Could you verify that you are modifying the value in your local.cfg *before* you build the backend?  As far as I can tell, this should all be working properly still.  Though, it is always possible that I'm overlooking something.

**Comment by parphis** [comment] 2024-07-11 17:02
@tdonohue 
Thanks for your check. I did/do the same as you. Just to be sure here are the points in details.

 1. `git clone git@github.com:DSpace/DSpace.git` First: `git checkout dspace-8_x` , second: `git checkout dspace-8.0` 
 2. Create the `local.cfg` file in the [src] folder and add this option line as the very first: `dspace.dir=/home/dspace/repozitorium`
 3. `rm -R ~/.m2` just to be sure and `mvn -U clean package`
 4. `less dspace/target/dspace-installer/webapps/server/WEB-INF/classes/application.properties` -> contains `dspace.dir=/dspace` and `logging.config = /dspace/config/log4j2.xml`

Interestingly, when I ran `git checkout dspace-7.6.1` with the same steps above the result was `dspace.dir=${dspace.dir}` and `logging.config = ${dspace.dir}/config/log4j2.xml` in the application.properties file.

I do not understand. What do I wrong? In which step these options are replaced by the compliler? I searched for the pom.xml but did not find any related.

**Comment by tdonohue** [comment] 2024-07-11 17:07
@parphis : Are you sure that you created the `local.cfg` in the proper directory?  It should be created under `[src]/dspace/config/` (alongside the `dspace.cfg` file and all other configs) and NOT in the root `[src]` folder.   

I suspect the issue may be that Maven is not finding your `local.cfg` because it's in an unexpected location.  If Maven cannot find the `local.cfg`, then it will always use the defaults in `[src]/dspace/config/dspace.cfg`.

**Comment by parphis** [comment] 2024-07-11 18:03
@tdonohue Thanks, you are right, that was my mistake with the wrong `local.cfg` path. Apologies for this.

What has remained interesting for me is why compiling the version 7.6.1 resulted in `dspace.dir=${dspace.dir}` option? Is this a pom.xml like thing or what?

**Comment by tdonohue** [comment] 2024-07-11 19:33
@parphis : I honestly don't know why the filtering behavior differs between 7.6.1 and 8.0 when the local.cfg cannot be found.   My suspicion is it may be related to the POM refactoring that occurred to create the new Runnable JAR in 8.0 (as this required some changes to the Maven POMs / build process). 

In any case, it sounds like this is working properly.  It's just defaulting to using the settings in `dspace.cfg` when the `local.cfg` cannot be found.  Closing this ticket as answered.

**Closed by tdonohue** 2024-07-11 19:33 UTC
Labels: bug, cannot reproduce, needs triage
