### ISSUE TITLE
Workflow items cannot be sent back to submitters (DSpace 7.5)

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#8726] opened 2023-03-17 12:44 UTC
**Describe the bug**
Using the Admin workflow, it not possible to send an item back to a submitter. It used to be possible in DSpace 7.4.

**To Reproduce**
This can be reproduce on DSpace Demo Site.

1. Connect as admin
2. In the left menu, clic on Administer workflow
3. In the Status Filter, select Workflow
4. On an item, clic on the Send back button.
5. In the _Send workflow item back to submitter_ page, scroll down and clic on the red Send back button.

Nothing happen.

**Expected behavior**
When using the Send back button, the item should leave the Workflow statuts to the Workspace statut. The user should be sent back to the Administer workflow page.

**Comment by pilasou** [comment] 2023-03-17 13:00
I noticed that the same problem occurs when using the Delete button in the Admin workflow (nothing happen when clicking on it). I am wondering if the problem cannot be related to the Supervision feature that has been introduced in 7.5.

**Comment by tdonohue** [comment] 2023-03-20 14:48
Closing as this is a duplicate of DSpace/dspace-angular#2118.  See that ticket for details.

**Closed by tdonohue** 2023-03-20 14:48 UTC
Labels: bug, needs triage
