### ISSUE TITLE
Identifier provider mocks can affect subsequent tests

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#9810] opened 2024-09-06 15:50 UTC
## Describe the bug
The mocked `IdentifierProvider` list in `VersionedHandleIdentifierProviderIT` can cause subsequent tess to fail.
This was partially covered in https://github.com/DSpace/DSpace/pull/9097 (wrt. to unchecked casts), but the list of providers should not persist outside of the original test suite.

Encountered due to random test order in #9735: `VersioningWithRelationshipsIT` fails when running directly after `VersionedHandleIdentifierProviderIT`

## Proposed solution
`VersionedHandleIdentifierProviderIT` should reset the `IdentifierProvider` list to the one provided in Spring XML after each test

**Comment by tdonohue** [comment] 2024-09-06 15:59
@ybnd : @kshepherd is already working on this in #9807   Please take a look at the work he's doing there before starting anything new.

**Comment by tdonohue** [comment] 2024-09-06 16:51
Closing as this is fixed in #9807 (which was just merged & is being backported)

**Closed by tdonohue** 2024-09-06 16:51 UTC
Labels: bug, testing framework

**Comment by ybnd** [comment] 2024-09-06 20:42
@tdonohue sorry about that, I rushed my "last thing before going home on Friday" a bit too much here...

If I understood correctly #9807 solved the issue on the side of `VersioningWithRelationshipsIT` though, can we be sure the mocked provider list can't affect other tests still?

**Comment by tdonohue** [comment] 2024-09-06 21:28
@ybnd : In #9807 see changes in `VersioningHandleIdentifierProviderIT` which reset the list of providers back to defaults by resetting the context.  I think this does the same general thing you were going for.  But, I'd refer your question to @kshepherd (as he did the deep digging here to see what was wrong & found a fix that works).

**Comment by kshepherd** [comment] 2024-09-07 08:03
hi @ybnd, thanks for the input, I think we both had the same idea at the same time ;)
From what I saw, `VersioningHandleIdentifierProviderIT` was the only class that was not resetting the provider beans after running tests. The other test that needed to set multiple providers, `CreateMissingIdentifiersIT` was properly resetting (and it is this `applicationContext.refresh` approach I re-used in my PR).

There is some follow-up work to do, because the failures we saw recently are a result of actual unexpected behaviour or bugs in the canonical provider, it just happens to be that it wasn't the provider used in a lot of tests! So we do need to look into that and probably change tests that are related to versioning or handles, to make sure both are tested.
(that could be a lot of work now that I think about it...)
