### ISSUE TITLE
Curation tasks don't provide any output on the task they performed

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8440] opened 2022-08-03 14:04 UTC
**Describe the bug**
When you run a curation task the output log will only contain output like:

> 2022-07-29 06:05:31.652 INFO curate - 203 @ The script has started
> 2022-07-29 06:06:31.293 INFO curate - 203 @ The script has completed

The rest of the output ends up in the log files.

**To Reproduce**
1. Go the admin curation workflow
2. Start any curation task were you expect some output (checklinks for example)
3. Wait for it to finish & view the output
4. It will only contain lines similar to the ones above.

**Expected behavior**
It should show all the output that is currently ending up the logs.

**Comment by KevinVdV** [comment] 2022-08-03 14:25
The fix itself should be fairly simple, in theory it just boils down to changing the log.info on the following places:
* https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/curate/Curator.java#L549
* https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/curate/Curator.java#L565

We should also log the system.out calls in the output, just search for that in the Curator.java class.

I estimate the work to fix to be around a day we would then:
* Ensure that the logs end up in the output
* tests that use the "NoOpCurationTask" & verify that the "No operation performed on " is added to the response

**Comment by tdonohue** [comment] 2022-08-03 14:35
@KevinVdV : This looks to be a duplicate of https://github.com/DSpace/dspace-angular/issues/1322...and the 4Science team is already working on fixing this in 7.4.

Closing this ticket as a duplicate of https://github.com/DSpace/dspace-angular/issues/1322. I'll copy your notes over to the existing ticket for the 4Science team to see.

**Closed by tdonohue** 2022-08-03 14:35 UTC
Labels: bug, tools: curation-tasks, needs triage
