### ISSUE TITLE
In DSpace 7.3, request copy acceptance email has NULL value as subject

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#8450] opened 2022-08-08 17:30 UTC
**Describe the bug**
In DSpace 7.3 when someone accept a copy request made on an embargo item, the email sent to the requester has NULL as subject.

We have the Helpdesk copy request feature configured (requests are not sent to the submitter).

**To Reproduce**
1. Ask for a copy of an embargo item
2. Follow the link provided in the request email and log in
3. Clic on the Accept request button.
4. On next page, clic on send.

The email will have NULL as subject.

**Expected behavior**
Subject of the email should be the one entered in the Subject field of the answer form.

**Comment by tdonohue** [comment] 2022-08-08 17:46
I was able to verify this on my local copy.  It's likely a small bug, but something we should definitely fix.  Pulling this over into the 7.4 board and flagging as `help wanted`. Hopefully we can find someone able to work on this for 7.4

**Comment by nwoodward** [comment] 2022-10-24 18:45
I did a little testing, and it appears the subject is getting set correctly at first. But then it gets reset to null in the send() method of Email where I think there's a logical error on line https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/core/Email.java#L358. It seems like the null check was intended for `headerValue` instead of `subject`. And since the `headerValue` is null in the case of the request copy acceptance email that's where the subject gets lost.

**Comment by tdonohue** [comment] 2022-10-24 18:56
@nwoodward : If you are able to create a PR for us, I'll get it assigned to some testers who can help verify this fixes the issue.  (It's difficult to tell at a glance, but if does appear like the null check is likely incorrect.)

**Closed** 2022-10-31 20:16 UTC
Labels: bug, high priority, backend: email-system, good first issue, help wanted
