### ISSUE TITLE
Previously failed ZIP exports will also fail subsequent ZIP exports 

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/DSpace#9499] opened 2024-04-24 11:50 UTC
**Describe the bug**
During the ZIP export through the UI, a temporary directory is created based on the UUID of the eperson doing the export.
If that export fails because of a missing bitstream for example, that temporary directory is never cleared.
Subsequent exports will try to create that directory as well, but that will automatically fail because the directory already exists

**To Reproduce**
1. Go to a random collection you want to export, a single item is sufficient
2. Access the DB, and break the bitstream/assetstore linking. (For example by altering the internal_id)
3. Try the export, it will fail because the bitstream can't be found
4. Fix any possible issues (For example by changing the internal_id back)
5. Export again -> it will fail again, with an error like: 
```
2024-04-24 11:38:33.504 ERROR export - 148 @ java.lang.Exception: java.lang.Exception: Directory /home/dspace/dspace/exports/saf-export-bbabd841-98f1-48f6-bb62-d54089931c15.zip/1 already exists!
```

**Expected behavior**
If a ZIP export fails in the DSpace codebase, it should either clear up the existing temporary export directory, or a subsequent export should at least not break it.

**Comment by tdonohue** [comment] 2024-04-24 13:57
Pulling this over to the 8.0 board as this seems to be a high priority bug to fix.  Needs a volunteer

**Comment by tdonohue** [comment] 2024-05-24 21:01
@abollini : Just a reminder that this ticket is assigned to 4Science.  If possible, it'd be good to see a PR in the next week as we are hoping to get this into 8.0.

**Comment by tdonohue** [comment] 2024-06-04 16:45
@abollini : I've found a way to fix this bug, so I'm claiming this ticket.  Please see #9629 for the fix.   I'll assign you as a reviewer, but feel free to delegate as needed.

NOTE: I've not found a way to reproduce this bug via unit/integration tests, so no tests are provided in the PR.  But, the PR is simply adding a new try/finally...and I've verified the bug is fixed by following the process that @jonas-atmire describes in this ticket for forcing a failure (by temporarily changing the `internal_id` of a bitstream) and then undoing the changes & verifying the export now works.

**Closed** 2024-06-06 14:52 UTC
Labels: bug, high priority, tools: export, testathon
