### ISSUE TITLE
Entity relationship ERROR: duplicate key value violates unique constraint Key (left_id, type_id, right_id)

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#8020] opened 2021-11-02 10:36 UTC
**Describe the bug**
At the Front-end, when trying to edit relationships I noticed an Internal Server Error (500 code) with
`POST https://MYSERVER/server/api/core/relationships?relationshipType=1`
With payload:
```
https://MYSERVER/server/api/core/items/d86be698-f2ae-4e79-8f54-97e08a75df7a 
 https://MYSERVER/server/api/core/items/1ab8fd28-353b-43d7-81b5-5572c95f7995

```
My dspace log had:
```
2021-11-02 10:07:25,072 INFO  e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [POST /server/api/core/relationships] originated from /entit
ies/publication/d86be698-f2ae-4e79-8f54-97e08a75df7a/edit/relationships
2021-11-02 10:07:25,112 INFO  e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2021-11-02 10:07:25,112 ERROR e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch e
ntry 0 insert into public.relationship (left_id, left_place, leftward_value, type_id, right_id, right_place, rightward_value, id) values ('d86be698-f2ae-4e79-8f54-97e08a75df7a'::uuid, -1, NULL, 1, '1ab8fd28-353b-43d7-81b5-5572c95f7995'::
uuid, -1, NULL, 68) was aborted: ERROR: duplicate key value violates unique constraint "u_constraint"
  Detail: Key (left_id, type_id, right_id)=(d86be698-f2ae-4e79-8f54-97e08a75df7a, 1, 1ab8fd28-353b-43d7-81b5-5572c95f7995) already exists.  Call getNextException to see other errors in the batch.], SQL: insert into public.relationship (l
eft_id, left_place, leftward_value, type_id, right_id, right_place, rightward_value, id) values (?, ?, ?, ?, ?, ?, ?, ?)
2021-11-02 10:07:25,113 WARN  e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ SQL Error: 0, SQLState: 23505
2021-11-02 10:07:25,113 ERROR e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ Batch entry 0 insert into public.relationship (left_id, left_place, leftward_value
, type_id, right_id, right_place, rightward_value, id) values ('d86be698-f2ae-4e79-8f54-97e08a75df7a'::uuid, -1, NULL, 1, '1ab8fd28-353b-43d7-81b5-5572c95f7995'::uuid, -1, NULL, 68) was aborted: ERROR: duplicate key value violates unique
 constraint "u_constraint"
  Detail: Key (left_id, type_id, right_id)=(d86be698-f2ae-4e79-8f54-97e08a75df7a, 1, 1ab8fd28-353b-43d7-81b5-5572c95f7995) already exists.  Call getNextException to see other errors in the batch.
2021-11-02 10:07:25,113 ERROR e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: duplicate key value violates unique constraint "u_constraint"
  Detail: Key (left_id, type_id, right_id)=(d86be698-f2ae-4e79-8f54-97e08a75df7a, 1, 1ab8fd28-353b-43d7-81b5-5572c95f7995) already exists.
2021-11-02 10:07:25,115 ERROR e6402fef-ff4d-442f-afbc-29b409ffb8f4 ffbea30c-a39d-4486-8cc0-c7c1cf41b541 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1535) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.dspace.core.AbstractHibernateDAO.executeCriteriaQuery(AbstractHibernateDAO.java:428) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:162) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.dao.impl.RelationshipDAOImpl.findByItemAndRelationshipType(RelationshipDAOImpl.java:183) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.RelationshipServiceImpl.findByItemAndRelationshipType(RelationshipServiceImpl.java:656) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.RelationshipServiceImpl.findByItemAndRelationshipType(RelationshipServiceImpl.java:634) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.RelationshipServiceImpl.updatePlaceInRelationship(RelationshipServiceImpl.java:128) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.RelationshipServiceImpl.create(RelationshipServiceImpl.java:101) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.content.RelationshipServiceImpl.create(RelationshipServiceImpl.java:90) ~[dspace-api-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.RelationshipRestRepository.createAndReturn(RelationshipRestRepository.java:128) ~[classes/:7.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
...
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:399) [tomcat-coyote.jar:9.0.30]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.30]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-coyote.jar:9.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) [tomcat-coyote.jar:9.0.30]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.30]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute batch
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:129) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:105) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:148) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:633) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:57) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:108) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1309) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1389) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        ... 150 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into public.relationship (left_id, left_place, leftward_value, type_id, right_id, right_place, rightward_value, id) values ('d86be698-f2ae-4e79-8f54-97e08a75df7a'::uuid, -1, NULL, 1, '1ab8fd28-353b-43d7-81b5-5572c95f7995'::uuid, -1, NULL, 68) was aborted: ERROR: duplicate key value violates unique constraint "u_constraint"
  Detail: Key (left_id, type_id, right_id)=(d86be698-f2ae-4e79-8f54-97e08a75df7a, 1, 1ab8fd28-353b-43d7-81b5-5572c95f7995) already exists.  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644) ~[postgresql-42.2.24.jar:42.2.24]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242) ~[commons-dbcp2-2.8.0.jar:2.8.0]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatc
...
 at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:57) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:108) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1309) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1389) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        ... 150 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "u_constraint"
  Detail: Key (left_id, type_id, right_id)=(d86be698-f2ae-4e79-8f54-97e08a75df7a, 1, 1ab8fd28-353b-43d7-81b5-5572c95f7995) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901) ~[postgresql-42.2.24.jar:42.2.24]
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644) ~[postgresql-42.2.24.jar:42.2.24]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242) ~[commons-dbcp2-2.8.0.jar:2.8.0]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242) ~[commons-dbcp2-2.8.0.jar:2.8.0]
...
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        ... 150 more

```

**To Reproduce**
(Please check the steps I did for https://github.com/DSpace/dspace-angular/issues/1387)
. At the lookup form, please wait for the relation to be set and after it click save

**Expected behavior**
Because relation might be created when you firstly choose the entity, when you click save button, a second call to `POST /relationships` will be made (that could be a DSpace Angular issue - I don't think so), but I was expecting the second request (same POST request) to be **idempotent**, reinforcing the relation, not generating an error.

**Related work**
https://github.com/DSpace/dspace-angular/issues/1387

**Comment by tdonohue** [comment] 2021-11-03 16:11
@paulo-graca : My suspicion is this error is caused by the invalid/unexpected configuration in your other ticket (see https://github.com/DSpace/dspace-angular/issues/1387#issuecomment-959576720).  

I'm not able to reproduce this error with the default Entities configuration of DSpace 7.1 when editing relationships. Unless I'm misunderstanding how to reproduce this....I just tried going to http://localhost:4000/entities/person/b1b2c768-bda1-448a-a073-fc541e8b24d9/edit/relationships and adding a new relationship.

**Comment by tdonohue** [comment] 2022-01-21 20:20
Closing as unreproducible. I think this is caused by https://github.com/DSpace/dspace-angular/issues/1387  However, if we find a way to reproduce, we can always reopen later.

**Closed by tdonohue** 2022-01-21 20:20 UTC
Labels: bug, component: configurable entities, needs triage

**Comment by tlloydthwaites** [comment] 2022-03-15 07:29
I am also getting this error periodically. I can't see a pattern, and I am not sure how to reproduce without sending a database dump.

**Comment by tlloydthwaites** [comment] 2022-03-21 02:32
Update: it occurs consistently for me when I add two relationships to the same entity, eg. isAuthorOfPublication and isEditorOfPublication to the same person. (Granted this is unusual, we are working with legacy data imported from eprints) but that seems to reliably trigger it for us.
