### ISSUE TITLE
Remove Rest Legacy REST API

### ISSUE THREAD

**Issue by misilot** [DSpace/DSpace#9219] opened 2023-12-04 16:34 UTC
**Describe the request**
Per the documentation for the REST API (https://github.com/DSpace/DSpace/tree/main/dspace-rest) it will be removed with version 8.

**Comment by tdonohue** [comment] 2023-12-04 16:45
Duplicate of #7643  We already have a ticket for this, so closing this one.

**Comment by misilot** [comment] 2023-12-04 16:46
Whoops, I looked but didn't see this one! Sorry about that

**Closed by tdonohue** 2023-12-04 16:45 UTC
Labels: bug, needs triage
