### ISSUE TITLE
Create New item Bug (Design bug) / DSpace 7.4

### ISSUE THREAD

**Issue by mhourani87** [DSpace/DSpace#8618] opened 2022-12-25 19:01 UTC
When create a new item , the list of language now shown correctly

**Comment by tdonohue** [comment] 2023-01-05 14:49
@mhourani87 : Could you provide step-by-step instructions or screenshots to reproduce the error you are seeing? I'm not understanding what the error is or how to reproduce it.

**Comment by mhourani87** [comment] 2023-01-05 22:03
hello, 
kindly find the attached file 

![image](https://user-images.githubusercontent.com/121402008/210888710-3a641c59-7be4-4e3b-909b-184426ed2856.png)

**Comment by tdonohue** [comment] 2023-01-11 20:31
I'm not able to reproduce this bug in a default 7.4 site.  It also cannot be reproduced on our demo site at https://demo7.dspace.org/   Therefore, I suspect it may be a local configuration issue or perhaps there's an error being thrown behind the scenes which causes this problem.

I'd recommend using our Troubleshooting guide to look for a more detailed error message (if one exists)  
https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

If you find a more detailed error message, feel free to send it (along with the steps you took to reproduce this error) to one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

For now, I'm closing this ticket as unreproducible. If someone is able to find a way to reproduce this in other sites, we can always reopen it as needed.

**Closed by tdonohue** 2023-01-11 20:31 UTC
Labels: bug, cannot reproduce, needs triage
