### ISSUE TITLE
Handle redirect for items not working

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/DSpace#3113] opened 2021-01-12 10:58 UTC
**Describe the bug**
The "pid" endpoint which is used to retrieve DSpace Objects based on a handle does not work for items.
The endpoint does however work to retrieve a collection/community when used with a handle.

TThis used to work when it was tested in angular PR [#934](https://github.com/DSpace/dspace-angular/pull/934).
There [do not seem to be any integration tests](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/IdentifierRestControllerIT.java) to verify the behavior for items, only for communities.

**To Reproduce**
Example: The item with ID [df376455-2790-434a-9957-5e1ba740fff9](https://dspace7.4science.cloud/server/api/core/items/df376455-2790-434a-9957-5e1ba740fff9) contains the handle '123456789/238'.
Therefore the following url should redirect to the corresponding item: https://dspace7.4science.cloud/server/api/pid/find?id=123456789%2F238
Instead it gives a 404 error.

**NOTE FROM TIM:** Note, this bug is ONLY reproducible if the Handle in question starts with a *different* prefix than the one specified in your `handle.prefix` setting.  If it has the *same* prefix, then the Handle redirect will work successfully.

**Expected behavior**
When the request is done with a valid item handle, the user should be redirected to the item page.

**Comment by tdonohue** [comment] 2021-01-12 22:25
@YanaDePauw : I am able to reproduce this on the 4Science demo site (as you noted).  However, I'm *not* able to reproduce this locally -- when running the REST API locally, the `/api/pid/find?id=` endpoint seems to work fine for Items.

This makes me wonder if we are hitting a configuration issue on the 4Science demo server...or maybe a more obscure bug that only affects some Items.  @abollini : Do you have any ideas what this might be?

**Comment by tdonohue** [comment] 2021-01-28 20:47
After more analysis, I've figured out what appears to be wrong here.

* Handle redirects for Items **work fine** if the Item's Handle starts with `handle.prefix` (configured in your local.cfg).  So, if I create a new Item, it's assigned Handle with start with that prefix & the redirect works.
* Handle redirects for Items **don't work** if the Item's Handle starts with anything else.  So, if I change the value of `handle.prefix` or import content from elsewhere, the redirect returns a 404.

I'm moving this to Beta 5 for estimation.

**Comment by tdonohue** [comment] 2021-01-28 20:48
@benbosman : would you (or someone on your team) be willing to look into this & provide an estimate?

**Comment by tdonohue** [comment] 2021-02-11 16:51
@benbosman : I'm assigning this to you (or someone on your team) to add an estimate.  Let me know if I need to reassign.

**Comment by benbosman** [comment] 2021-02-25 13:32
I've verified this in more detail, and the whole principle should be changed (not just a backend fix)

What happens now is:
* Angular creates a call to /server/api/pid/find?id=123456789/523
* This is caught by REST, and sent to the IdentifierProviders
* If an IdentifierProvider states it can resolve it, it will return the DSO

But this is used for handle, DOI, EZID, … without any knowledge of the type of ID
It should not be up to REST to guess the type of ID, especially since there can be overlap

What I'd suggest:
* Angular makes the call to /server/api/pid/find?id=123456789/523&type=handle (AFAIK Angular only makes calls for the handle)
* org.dspace.identifier.service.IdentifierService#resolve is overloaded to add an optional type
* org.dspace.identifier.IdentifierProvider#supports is overloaded to add an optional type
* org.dspace.identifier.HandleIdentifierProvider#supports will say yes to type "handle" if it matches one of the configured prefixes
* org.dspace.identifier.HandleIdentifierProvider#supports will remove support for "hdl:", "info:hdl", … since it doesn't support it in org.dspace.identifier.HandleIdentifierProvider#resolve

An alternative would be to deal with the type in de id value:
* Angular makes the call to /server/api/pid/find?id=hdl:123456789/523
* org.dspace.identifier.HandleIdentifierProvider#resolve is adjusted to support this syntax (since it claims it's supported in org.dspace.identifier.HandleIdentifierProvider#supports)

But the problem we have right now:
* org.dspace.identifier.HandleIdentifierProvider#supports states it supports "hdl:123456789/523" independent of the config, but states it only supports "123456789/523" if the prefix is configured
* org.dspace.identifier.HandleIdentifierProvider#resolve can resolve 123456789/523 to an item, independent of the config, but can't resolve "hdl:123456789/523" at all

Specifically to the problem of https://api7.dspace.org/server/#/server/api/pid/find?id=123456789%2F238 not working:
* The prefix 123456789 has to be configured on the api7.dspace.org server as handle.canonical.prefix
* An IT has to be created for resolving items, but that does require a strategy for fixing the HandleIdentifierProvider inconsistency is chosen first

**Comment by tdonohue** [comment] 2021-02-25 22:27
@benbosman : I see your point here. I think I lean ever so slightly towards your **alternative** option just because it seems like a quicker, simple solution.  Correct me if I'm wrong, but it also seems like it'd take very little effort -- maybe 2 hours on the Angular side and 2-4 on REST -- as the changes seem minor to me.  Do you feel those estimates are reasonable, or do you feel it'd take more effort? 

That said, I vaguely recall that @abollini may have built this `/server/api/pid/find?id=` endpoint (very early on).  Do you have any quick feedback on this @abollini ?

**Comment by benbosman** [comment] 2021-03-04 10:50
@tdonohue That sounds good to me. With tests included, I'd assume REST will require the 4 hours

So 2 hours Angular and 4 hours REST should be sufficient for the solution:
* Angular makes the call to /server/api/pid/find?id=hdl:123456789/523
* org.dspace.identifier.HandleIdentifierProvider#resolve is adjusted to support this syntax (since it claims it's supported in org.dspace.identifier.HandleIdentifierProvider#supports)
* org.dspace.identifier.HandleIdentifierProvider#resolve and org.dspace.identifier.HandleIdentifierProvider#supports will be implemented consistently, what's supported will also be parsed correctly to resolve
* Tests are created for handles on the `/pid/find` endpoint using the `hdl:` prefix

**Comment by abollini** [comment] 2021-03-04 16:33
I like this solution. It is my understanding that only the HandleIdentifierProvider will be modified (maybe we should check also the Versioned one) to properly resolve **also** the handles prefixed with hdl:

**Closed** 2021-03-30 14:49 UTC
Labels: REST API v7, bug, e/6
