### ISSUE TITLE
Can't delete workflow itens

### ISSUE THREAD

**Issue by leandroecomp** [DSpace/DSpace#9095] opened 2023-09-29 10:43 UTC
**Describe the bug**
Hi there. We are unsing DSpace 7.5. I'm having problems editing workflow items. The database was imported from DSpace 6.1.2017.

**To Reproduce**
In an attempt to delete some submissions, we are redirected to another page, as shown in the attached image:
![image](https://github.com/DSpace/DSpace/assets/46628962/69f1b311-0562-48cb-8477-a3bcc8e25d29)

However, when pressing 'Delete', nothing happens as if the button was deactivated.

![image](https://github.com/DSpace/DSpace/assets/46628962/0d662cc9-f830-4cea-b77f-0bab425161e0)

Has anyone experienced a similar event?

**Comment by tdonohue** [comment] 2023-10-02 14:28
Closing, as this is a duplicate of https://github.com/DSpace/dspace-angular/issues/2118   This bug was fixed in the 7.6 release.

**Closed by tdonohue** 2023-10-02 14:28 UTC
Labels: bug, needs triage
