### ISSUE TITLE
Community/Collection admins can't edit logo for communities/collections

### ISSUE THREAD

**Issue by steph-ieffam** [DSpace/DSpace#9314] opened 2024-02-09 12:18 UTC
**Describe the bug**
Currently there’s a bug for the edit of community/collection logo.

The edit only works if an administrator is editing the logo but if a Collection/Community admin (not Administrator standard user but has permission to administrate specific community/collection) tries to modify the logo a 403 error code is returned by the rest application

**To Reproduce**
1. Login with a community/collection administrator account
2. Try to edit a logo in one of the administered community/collection

**Expected behavior**
Rest should no longer return 403 error code and the logo is successfully uploaded

**Comment by tdonohue** [comment] 2024-02-09 14:27
This is a duplicate of a ticket in the `dspace-angular` GitHub issues: https://github.com/DSpace/dspace-angular/issues/2240

Closing this in favor of the other ticket, just to keep all the info in one place.

**Closed by tdonohue** 2024-02-09 14:27 UTC
Labels: bug, needs triage
