### ISSUE TITLE
Possible to login back to Shibboleth account with any not registered e-mail account after Shibboleth logout

### ISSUE THREAD

**Issue by parphis** [DSpace/DSpace#9109] opened 2023-10-05 10:31 UTC
**Describe the bug**
DSpace 7.6 / Debian 11

I have tested my Angular customizations regarding the new user registration and forgot password pages and finally found a very strange thing.
In one step, the registration of the new user was unsuccessful _because of my issue_. But I did not know my issue at this time so I logged in with my Shibboleth account and made some search for the new user. I did not find this user but I was interrupted for some minutes. Then coming back to this thread again I forgot where I left the process so I logged out from the Shibboleth account and I tried to log in with the new user account - which was not created due to my issue. And I saw my Shibboleth account details instead of the new user one.

Later I solved my Angular issues but this problem remained and is reproducible.

I tested the Dspace 6.3 and it works as expected: the login with an e-mail account is impossible if the user logged out before.

It seems that this issue is not a Shibboleth timeout related one.

**To Reproduce**
Go to your DSpace site and login with a valid Shibboleth account.
Do nothing just press the _Log out_ button to logout from that Shibboleth session.
Using the same browser window / session try to log in with a simple account: open the Log in form and enter any kind of valid formatted e-mail address into the e-mail address field of the login form. E.g. dummy@dummy.com. Then enter any kind of password. E.g. a single 'a' is enough.
Press the _Log in_ button and you can see your previous Shibboleth session which is usable not just a browser cached page.

**Expected behavior**
If a user presses the _Log out_ button any account related sessions should be closed.

**Related work**
Not known

**Comment by parphis** [comment] 2023-10-16 06:58
@tdonohue Yes, the config had Shibboleth auth. first:

Original plugin order was:
```
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.ShibAuthentication
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.IPAuthentication
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.PasswordAuthentication
```
However, changing the plugin order to this:
```
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.PasswordAuthentication
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.ShibAuthentication
plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.IPAuthentication
```
did not solve this issue.

I also tried to merge the https://github.com/DSpace/DSpace/pull/2758 PR into the current source without success. A lots of things has changed since 2020 and I do not have time and knowledge to merge them and/or to implement the SAML login process.

**Comment by amgciadev** [comment] 2023-12-11 13:11
Hi, we are currently at the testing stages of 7.6.1 in one of our dev environments but we are not able to reproduce this issue. Can I confirm that the steps are:

1. Log in via Shibboleth
2. Logout
3. Attempt to log in using email authentication (inc. an invalid password)
4. The user logged in is the previously Shib logged in user rather than the user associated via email and credentials supplied.

Just checking that we are testing this as expected.

**Comment by parphis** [comment] 2023-12-12 13:55
Hello, yes those are the exact steps to reproduce this issue. I just tested it again and I was able to reproduce it.

The order of the authentication plugins do not change the result as well as the browser type does not change anything. I also have tested it with private browser mode with the same result.

Here we have a dev and a production environment both are running DS 7.6.1 (same for backend and ui) on Debian 11.8 with 12GB mem and Intel Xeon E3-1200.

It is clear that the Shibboleth session remains for some time within one browser session. So when you login in with Shibboleth then log out and log in back with Shibboleth within e.g. 1 minute then you do not need to enter your credentials again because of the session is still alive. But this should not happen when you log out from a Shibboleth session but another person tries to log in with any e-mail account.

Thanks for taking on this!

**Comment by amgciadev** [comment] 2023-12-20 14:50
Hi, how strange: before we were not able to reproduce this error and Shibboleth auth was working for us in the same way as DSpace 7.6. Since today Shibboleth is no longer working for us in chrome and firefox but works fine in Safari. The only thing that has changed is that I've upgraded chrome in my laptop. I am now not able to log in using shibboleth at all. Errors I get in the dev tools are:

main.a6c6e383992c087c.js:1 ERROR Error: undefined doesn't contain the link authn
    at main.a6c6e383992c087c.js:1:377132
    at main.a6c6e383992c087c.js:1:2789596
    at c._next (main.a6c6e383992c087c.js:1:2785616)
    at c.next (main.a6c6e383992c087c.js:1:2774416)
    at main.a6c6e383992c087c.js:1:2789589
    at c._next (main.a6c6e383992c087c.js:1:2785616)
    at c.next (main.a6c6e383992c087c.js:1:2774416)
    at main.a6c6e383992c087c.js:1:2793871
    at c._next (main.a6c6e383992c087c.js:1:2785616)
    at c.next (main.a6c6e383992c087c.js:1:2774416)
handleError @ main.a6c6e383992c087c.js:1

See also screenshot. If after unsuccessfully having attempted a shibboleth login, I then try to log in using user and password I then get logged in as the previously attempted shibboleth login. This is a real blocker for us upgrading to 7.6.1.

![Screenshot 2023-12-20 at 14 45 47](https://github.com/DSpace/DSpace/assets/26137686/f7f4f1c5-a062-4f46-9e94-c067bfb41294)

**Comment by amgciadev** [comment] 2023-12-20 15:05
Some further testing results in different browsers:

**Windows**
Chrome Version 120.0.6099.72 (Official Build) (64-bit) - Shibboleth login works
Firefox: 120.0.1 (64-bit) - Shibboleth login works
Firefox: 121.0 (64-bit) - Shibboleth login works

**Mac**
Chrome Version 120.0.6099.109 (Official Build) (x86_64) - Shibboleth broken
Firefox 120.0.1 (64-bit) - Shibboleth broken
Firefox 121.0 (64-bit) - Shibboleth broken
Safari Version 17.1 (18616.2.9.11.10, 18616) - **Shibboleth works**

**Comment by tdonohue** [comment] 2023-12-20 15:05
@amgciadev : It's possible the Shibboleth issues you see in 7.6.1 are the ones described in https://github.com/DSpace/dspace-angular/issues/2669  This is unfortunately a known bug. There is a possible solution though in https://github.com/DSpace/dspace-angular/pull/2670 which appears to fix the issue.  It's still under final review though & not yet merged (though it seems to fix the Shibboleth issues for most).

**Comment by amgciadev** [comment] 2023-12-20 15:09
@tdonohue from the description in those issues it looks like that's the bug! What remains a mystery is all the different behaviours in browsers, and the fact that for the past week we've been testing 7.6.1 in our test server and we haven't experienced this at all in Chrome, until today (when I recently upgraded Chrome)

**Comment by amgciadev** [comment] 2023-12-20 21:46
@tdonohue I've incorporated the changes in  PR2670 in our 7.6.1 dev server and the Shibboleth issues seem to be fixed. We'll keep an eye on when the final version of that PR is merged. Thanks!

**Comment by tdonohue** [comment] 2024-05-01 17:35
Appears to be a duplicate of #8475 .  Closing in favor of that ticket.

**Closed by tdonohue** 2024-05-01 17:35 UTC
Labels: bug, authentication: Shibboleth, needs triage
