### ISSUE TITLE
Community/Collection admins can't edit logo for communities/collections

### ISSUE THREAD

**Issue by eskander17** [DSpace/DSpace#9319] opened 2024-02-09 16:36 UTC
**Describe the bug**
Community or Collection admins can't edit logo for communities or collections

**To Reproduce**
1. delete/create community logo by community's admin
2. delete/create collection logo by collection's admin

**Expected behavior**
Community/Collection admins can edit logo for communities/collections.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2024-02-09 17:32
This is a duplicate of https://github.com/DSpace/dspace-angular/issues/2240.   Linking those issues together.

**Closed** 2024-02-22 12:57 UTC
Labels: bug, duplicate
