### ISSUE TITLE
User Interface not starting in developer mode in DSpace 7.6

### ISSUE THREAD

**Issue by subratlubu** [DSpace/DSpace#9015] opened 2023-08-04 17:15 UTC
I have installed DSpace 7.6 both backend and frontend successfully. When I tried to start the user interface in developer mode the following error occurs. But in production mode it is working fine. Kindly help me to resolve the issue.

![Dspace7 6](https://github.com/DSpace/DSpace/assets/58173344/150e2593-9cbb-45e9-822a-2aa87cec7108)

**Comment by tdonohue** [comment] 2023-08-04 17:28
Closing, this is a duplicate of https://github.com/DSpace/dspace-angular/issues/2259

You can fix this by giving Node more memory, e.g. `export NODE_OPTIONS=--max-old-space-size=4096` will give Node up to 4GB of memory.

If you need further help/support, use our support options at https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2023-08-04 17:28 UTC
Labels: bug, needs triage
