### ISSUE TITLE
Stability of the example/test data used by the `cli.ingest.yml` file

### ISSUE THREAD

**Issue by dpk** [DSpace/DSpace#9927] opened 2024-10-29 11:58 UTC
We are planning to add a test suite to our [Python REST client library for DSpace](https://github.com/the-library-code/dspace-rest-python).

It would be useful to be able to consistently run this test suite against an example instance with a known set of data in it. For this we would [like to use the AIP or database dump](https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+8#TryoutDSpace8-InstallviaDocker#:~:text=Next%2C%20optionally%2C%20you%20can%20add%20test%20data%20to%20your%20Docker%20instance) provided for setting up test instances. However, we don’t want tests to start breaking just because future versions of this AIP might be released with different contents.

Is there a stability or versioning policy in place for the testing AIP data?

**Comment by tdonohue** [comment] 2024-10-29 14:04
@dpk : The AIP data should likely NOT be used for tests, as it's extremely basic data (and not at all realistic).

For the User Interface e2e tests, we use the **Entities Test Data** (in `db.entities.yml` and `cli.assetstore.yml`) as our official test data.  See the build scripts in `dspace-angular` here: https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml#L117-L123

That data set is therefore more "stable", because it's used by DSpace's own e2e tests.  That said, because it is test data, we may still chose to change it in the future at some point...so, depending on it is at your own risk.  We don't have any versioning policy on test data, nor any way to notify people if we change our test data.

Closing this as answered.  It's not a bug, just a question.

**Closed by tdonohue** 2024-10-29 14:04 UTC
