### ISSUE TITLE
Error on applying migration V7.6_2024.05.07__process_eperson_constraint.sql

### ISSUE THREAD

**Issue by rafaelse** [DSpace/DSpace#9731] opened 2024-07-31 02:17 UTC
## Describe the bug

I'm trying to upgrade from v7.6.1 to v7.6.2, but I get an error when I run the migrations with the command `bin/dspace database migrate ignored`:

```
SQL State  : 55000
Error Code : 0
Message    : ERROR: cannot use a deferrable unique constraint for referenced table "eperson"
Location   : org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2024.05.07__process_eperson_constraint.sql (/usr/local/tomcat/file:/dspace/lib/dspace-api-7.6.2.jar!/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2024.05.07__process_eperson_constraint.sql)
Line       : 13
Statement  : -- Add new constraint where process.user_id is nullified if referenced EPerson is deleted.
ALTER TABLE process ADD CONSTRAINT process_eperson FOREIGN KEY (user_id) REFERENCES EPerson(uuid) ON DELETE SET NULL
```

Is there any solution or workaround for this issue?

We are using PostgreSQL version 13.15 on RDS.

**Comment by tdonohue** [comment] 2024-07-31 20:38
@rafaelse : This error doesn't make sense to me, and I'm not able to replicate it locally in DSpace 7.6.2.  Have you made any customizations to the database tables in your DSpace site?  For instance, have you added any custom migrations or manually changed anything in the "eperson" table?  Are you running DSpace with any custom plugins or similar?

I think we may need more information to understand what might be going on. This is definitely not normal behavior.  It's possible you've found a bug, but it's also possible you have local customizations that are causing this error to occur.

**Comment by rafaelse** [comment] 2024-08-01 16:54
Our team are just gaining custody of DSpace at our university and we are in the process of upgrading from v5 to v7, so I don't really know if there were any customization to the database in the past.

We sort of managed to solve this problem by deleting all constraints associated with the `uuid` column in table `eperson` and recreating them without the instructions `deferrable initially deferred`. After that, the migration ran seamlessly.

**Comment by tdonohue** [comment] 2024-08-01 17:02
@rafaelse : Thanks for that follow-up information.  From what I see, DSpace has **never** used `deferrable initially deferred` in any of it's SQL migrations (I cannot find it in the current 7.x or 8.x codebase or in the 5.x codebase).  So, I suspect this was a customization made to your database in the past (or perhaps an older installation of your database somehow defaulted to including `deferrable initially deferred` on all created constraints).  I don't see any code in DSpace that would have created constraints in this way.

Because I cannot find `deferrable initially deferred` in the DSpace codebase, and I cannot reproduce this locally, I'm going to close this ticket as "Answered".

However, if someone in the future also encounters this, we can always reopen it for further analysis as needed.

**Closed by tdonohue** 2024-08-01 17:02 UTC
Labels: bug, backend: FlywayDB
