### ISSUE TITLE
Internal server errors when retrieving entries for externalsources

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#2981] opened 2020-09-24 11:23 UTC
**Describe the bug**
Currently, on the demo rest api, the `/api/integration/externalsources/<:source-name>/entries` endpoint throws a 500 in many situations:
- sherpaJournal, sherpaPublisher and pubmed always return a 500 when you use their entries link
- orcidV2 crashes for certain queries, or if a query does work it can crash on certain pages.

It is possible that this is due to configuration errors and not code bugs.

**To Reproduce**
- Go to [/api/integration/externalsources](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources) and use the entries link on the following sources
	- sherpaJournal: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/sherpaJournal/entries?query=)
	- sherpaPublisher: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/sherpaPublisher/entries?query=)
	- pubmed: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/pubmed/entries?query=)

	
- Go to [/api/integration/externalsources](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources), and follow the link for orcidV2.
	- fill in the query "yes", and you'll get a 500: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=yes)
	 - fill in the query "test" and that will work: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=test)
	- but click on the "last" link and you'll get a 500: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=test&page=5758&size=20) 

**Expected behavior**
They should never throw a 500 if you pass valid parameters. If there are no results I'd expect an empty paginated response

**Comment by tdonohue** [comment] 2020-10-15 20:09
I'm able to reproduce this exact same behavior locally, when running the REST API via Docker.

In the DSpace logs, all these 500 exceptions are `NullPointerException`s.  Here's some examples from the logs.

When accessing orcidV2 with a query of "yes" ( http://localhost:8080/server/#http://localhost:8080/server/api/integration/externalsources/orcidV2/entries?query=yes), this is the error:
```
2020-10-15 19:58:34,911 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.NullPointerException: null
        at org.dspace.external.provider.impl.OrcidV2AuthorDataProvider.convertToExternalDataObject(OrcidV2AuthorDataProvider.java:122) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.external.provider.impl.OrcidV2AuthorDataProvider.lambda$searchExternalDataObjects$0(OrcidV2AuthorDataProvider.java:212)
~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.dspace.external.provider.impl.OrcidV2AuthorDataProvider.searchExternalDataObjects(OrcidV2AuthorDataProvider.java:212) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.external.service.impl.ExternalDataServiceImpl.searchExternalDataObjects(ExternalDataServiceImpl.java:64) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository.getExternalSourceEntries(ExternalSourceRestRepository.java:73) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository$$FastClassBySpringCGLIB$$62b12abd.invoke(<generated>) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository$$EnhancerBySpringCGLIB$$dae998d2.getExternalSourceEntries(<generated>)
~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.ExternalSourcesRestController.getExternalSourceEntries(ExternalSourcesRestController.java:64) ~[classes/:7.0-beta5-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
....
```

(As Art noted though, the `orcidV2` search works perfectly if I use "test" as the search.)

Similarly, if I try `sherpaJournal` with "test" (http://localhost:8080/server/#http://localhost:8080/server/api/integration/externalsources/sherpaJournal/entries?query=test), I get: 
```
2020-10-15 20:00:52,608 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.NullPointerException: null
        at org.dspace.app.rest.converter.ConverterService.toRestPage(ConverterService.java:232) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository.getExternalSourceEntries(ExternalSourceRestRepository.java:76) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository$$FastClassBySpringCGLIB$$62b12abd.invoke(<generated>) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.ExternalSourceRestRepository$$EnhancerBySpringCGLIB$$dae998d2.getExternalSourceEntries(<generated>)
~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.ExternalSourcesRestController.getExternalSourceEntries(ExternalSourcesRestController.java:64) ~[classes/:7.0-beta5-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
```

Both errors are quite similar, but the line numbers don't match up exactly.
* In the case of `sherpaJournal`, the NPE seems to occur when converting the `ExternalDataObject`s (results) into `ExternalSourceEntryRest` (page of Rest objects) here: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ExternalSourceRestRepository.java#L76
* In the case of `orcidV2`, the NPE may just be from no results coming back.  It looks like this is the line where an NPE happens: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/external/provider/impl/OrcidV2AuthorDataProvider.java#L122


@benbosman : as noted in today's meeting, I'm assigning this to you (or one of your team members) to estimate. Thanks!

**Comment by jonas-atmire** [comment] 2020-10-29 12:59
This is estimated this at around **_3 hours_** of implementation time
This includes both the implementation as well as the testing of the changes (See additional point related to the entries links as well, which will take up most of the investigation time)

For future reference, some notes/reiterations on the different problems:
* **sherpaJournal/sherpaPublisher** -> `NPE` -> The ['searchExternalDataObjects' in SherpaJournalDataProvider](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/external/provider/impl/SherpaJournalDataProvider.java#L160) returns null, while it SHOULD simple return an empty list similar to [other providers](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/external/provider/impl/LCNameDataProvider.java#L120)
* **orcidV2** -> `NPE` -> This is indeed because there are NO results coming back. 
    * We will need to add in some additional nullpointer checks. This will make sure that the code does not try to retrieve information from the 'person' that SHOULD be returned -> Existing ['name' information retrieval](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/external/provider/impl/OrcidV2AuthorDataProvider.java#L127) should be wrapped in  these nullpointer checks
* **Entries link in externalsources** In addition to that, it seems that the [externalsources](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/) endpoint does NOT adhere to the actual rest contract.
In the [rest contract](https://github.com/DSpace/Rest7Contract/blob/main/external-authority-sources.md), the `externalsource.links.entries` do not contain the query parameter -> If required, we will also investigate where this incorrect query is coming from (This Issue is more related to the passing of 'valid parameters', so not sure if we need to take this up in this issue or not)

**Closed** 2020-12-11 18:48 UTC
Labels: REST API v7, bug, e/3, tools: external-sources
