### ISSUE TITLE
In DSpace 7, when authentication is limited to LDAP, the user/password field are not displayed.

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#8389] opened 2022-06-30 19:00 UTC
**Describe the bug**
When LDAP is set up as the only authentication method (plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.LDAPAuthentication), the user is not able to enter a user name or password. The fields are not displayed as illustrated below.

![no-login-field](https://user-images.githubusercontent.com/19291880/176755747-80a16852-0676-4c31-9724-cda5c6fea6c0.png)

We are running DSpace 7.2.

As a workaround, we also used the Password method (#plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.PasswordAuthentication) with the configuration "user.registration = false."

**To Reproduce**
1. Comment all authentication method except: plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.LDAPAuthentication
2. Clic on Log in

The window is empty.

**Expected behavior**
The user can see the 2 connexion fields (username and password) when only LDAP connexion is used.

**Comment by tdonohue** [comment] 2022-07-01 15:27
Duplicate of #8312 .  Closing as a duplicate.

**Closed by tdonohue** 2022-07-01 15:27 UTC
Labels: bug, needs triage
