### ISSUE TITLE
Bad request when attempting to add 'Start Date' to Bitstream policies

### ISSUE THREAD

**Issue by AndrewZachWood** [DSpace/DSpace#7970] opened 2021-09-30 17:37 UTC
When attempting to set the start date of a bitstream policy, from the Admin edit context, I get a Bad Request error in my console which is reflected in my DSpace logs and the start date is not saved for the respective policy.
Video of me recreating the issue:
https://www.awesomescreenshot.com/video/5447262?key=f4124c5dc883c3203e5c961707ce3517

Error from my DSpace log:
```
2021-09-30 13:25:54,792 INFO  b081c14d-7544-4790-a8ab-2442fbbd9498 fdfea1cc-ce24-4515-94ec-fab3b962fb66 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [PATCH /server/api/authz/resourcepolicies/329] originated from /bitstreams/7da4dedc-05a1-4474-8af3-2f54602e70c2/edit
2021-09-30 13:25:54,802 ERROR b081c14d-7544-4790-a8ab-2442fbbd9498 fdfea1cc-ce24-4515-94ec-fab3b962fb66 org.dspace.app.rest.RestResourceController @ Attempting to replace a non-existent start date value.
org.dspace.app.rest.exception.DSpaceBadRequestException: Attempting to replace a non-existent start date value.
        at org.dspace.app.rest.repository.patch.operation.resourcePolicy.ResourcePolicyUtils.checkResourcePolicyForExistingStartDateValue(ResourcePolicyUtils.java:49) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.patch.operation.resourcePolicy.ResourcePolicyStartDateReplaceOperation.perform(ResourcePolicyStartDateReplaceOperation.java:45) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.patch.ResourcePatch.performPatchOperation(ResourcePatch.java:58) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.patch.ResourcePatch.patch(ResourcePatch.java:42) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.ResourcePolicyRestRepository.patch(ResourcePolicyRestRepository.java:320) ~[classes/:7.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:774) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.ResourcePolicyRestRepository$$EnhancerBySpringCGLIB$$266e186b.patch(<generated>) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.patch(DSpaceRestRepository.java:407) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) ~[classes/:7.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.ResourcePolicyRestRepository$$EnhancerBySpringCGLIB$$266e186b.patch(<generated>) ~[classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.patchInternal(RestResourceController.java:707) [classes/:7.1-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.patch(RestResourceController.java:661) [classes/:7.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by AndrewZWood** [comment] 2021-09-30 18:11
Maybe I'm not seeing the forest through the trees. But what is the purpose of this method?
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/[…]ository/patch/operation/resourcePolicy/ResourcePolicyUtils.java

As in, why is that check required when doing the PATCH operation to update a ResourcePolicy?

When comment out this line:
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/resourcePolicy/ResourcePolicyStartDateReplaceOperation.java#L45

It solves the issue but, as I said I'm not fully understanding the purpose of the code in the first place.

**Comment by tdonohue** [comment] 2021-09-30 18:38
@AndrewZWood : A quick answer to your question is because of the definition of how `PATCH` works (based on the JSON Patch specification).  Based on those specs, a `replace` **requires that a value already exist to replace**.  If no value already exists, you are supposed to send an `add` request.  See our REST Contract at https://github.com/DSpace/RestContract/blob/main/patch.md

Your video link doesn't work for me (it requires a login), so I cannot tell if you are hitting this bug from the UI, or if it's from your own REST API call.  If it's the latter, it may not be a bug, but you just need to do an `add`.  If it's from the UI, then it sounds like a bug in the UI code...it should be sending an `add` instead of a `replace`.

**Comment by AndrewZWood** [comment] 2021-09-30 18:40
@tdonohue Sorry about the link. Updated now so it should work. But yes, I am hitting the bug from the UI. I'll poke around the UI code 👍 .

**Comment by AndrewZWood** [comment] 2021-10-01 15:58
@tdonohue Update:
It seems that: https://git.atmire.com/clients/iastate-7-angular/-/blob/main/src/app/core/data/default-change-analyzer.service.ts#L25-27

Is returning the incorrect operator for the request E.G:
Given old Resource Policy:
https://imgur.com/JYQE0Su

And our updated resource policy:
https://imgur.com/VToXv5J

Our comparator returns:
https://imgur.com/8CYNGrY

Which is incorrect .

**Comment by cwilper** [comment] 2021-10-01 17:25
I have been following along with Andrew over here, and on further consideration, I think the problem is actually on the server side in this case, because a JSON object member with a value of `null` is not the same as one without the member. ( `{ } != { foo: null }` )

In general, if the REST API expresses the value of a field as `null` (and not just missing), [as it does in the case of resource policies](https://github.com/DSpace/RestContract/blob/main/resourcepolicies.md), it should accept `replace` operations for that field.

![](https://quickdrop.s3.amazonaws.com/2Mmp8ogqD77v/Screen+Shot+2021-10-01+at+12.50.46+PM.png)

So I think the angular code is doing the right thing in this case. Interestingly, it should also accept an `add` in this case, because as [section 4.1 of the JSON Patch spec](https://datatracker.ietf.org/doc/html/rfc6902#section-4.1) states regarding `add`:

> If the target location specifies an object member that does exist, that member's value is replaced.

**Comment by tdonohue** [comment] 2021-10-01 21:32
@cwilper : That does sound more like a REST API bug.  The REST API likely shouldn't return a `null` values in that case.

If either of you find the exact bug, I'd welcome a PR.  In the meantime, I'll move this over to our currently active board, but it'll likely have to wait for a volunteer to find time.

**Comment by tdonohue** [comment] 2023-02-21 22:56
This no longer appears to be reproducible in 7.5.  Closing as "fixed" as Start Date can now be added successfully from the Edit Bitstream page in an archived Item.

**Closed by tdonohue** 2023-02-21 22:56 UTC
Labels: bug, authorization, medium priority, help wanted
