### ISSUE TITLE
Solr date item.lastmodified of OAI-Index is wrong if local timezone has an offset to UTC

### ISSUE THREAD

**Issue by christian-scheible** [DSpace/DSpace#8558] opened 2022-10-31 10:32 UTC
**Describe the bug**
When an item get's indexed in the OAI-Solr-Index the timezone information get's lost. This leads to a wrong date in the OAI index.
The reason is, that the databases timestamp with timezone gets transformed to a [java.sql.Timestamp](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/Item.java#L74). That is when the timezone information get's lost. Later the [XOAI solr date formatter adds a Z for Zulu time zone](https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L447) without knowing about the original timezone of the timestamp.

So this Database timestamp with timezone:
2022-10-27 10:07:43.934+02 becomes this java.sql.Timestamp:
2022-10-27 10:07:43.934 becomes this Solr date:
2022-10-27T10:07:43.934Z

Which means that the Solr date is 2 hours ahead of the Database timestamp (and wrong).

To prevent this I added this to the XOAI class:
```
if(lastChange != null) {
            lastChange = new Date(lastChange.getTime() - TimeZone.getDefault().getOffset(lastChange.getTime()));
        }
return lastChange;
```

at this [line](https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L393)

This is not really a nice solution. I would be glad if someone would find a cleaner bug fix.

**To Reproduce**
1. Add a timestamp to the database that differs from UTC
2. Index the item using: `$ JAVA_OPTS="-Xmx1024M -Xms1024M -Dfile.encoding=UTF-8" && [dspace-folder]/bin/dspace oai import`
3. Compare timestamp in database with date of item.lastmodified in OAI-Index

**Expected behavior**
The timestamps should not differ between database and Solr Index

**Comment by tdonohue** [comment] 2022-10-31 15:05
@christian-scheible : While I haven't tested it yet, a slightly better fix might be to use `java.time.Instant` when [getting the current date/time on this line](https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L386)

It might be possible to just change that line to something like:
```
Date now = Date.from(Instant.now());
```

I'm not sure if that'll fix the problem or not, so definitely test it first.  But, I suspect the issue is with that `new Date()` which is probably grabbing the current date in local time instead of UTC.

**Comment by ichbineinusername** [comment] 2022-11-02 08:25
@tdonohue. Thanks for your suggestion, but unfortunately this won't help in this case because `now` is not the date that gets returned. It's the date from [item.getLastModified()](https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L384).

**Comment by christian-scheible** [comment] 2022-11-02 08:26
@tdonohue. Thanks for your suggestion, but unfortunately this won't help in this case because `now` is not the date that gets returned. It's the date from [item.getLastModified()](https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L384).

**Comment by uofmsean** [comment] 2023-06-20 22:35
I encountered this issue when our OAI indexing was reprocessing items for DSpace 7.5. I think the solution would be to set the UTC timezone for the [SimpleDateFormatter in SolrUtils.getDateFormatter()](https://github.com/DSpace/DSpace/blob/4ea5426d619ba5e2ca0cf0f41d845c371e066ff2/dspace-api/src/main/java/org/dspace/util/SolrUtils.java#L38). This method is used in other places and resulting in other cases where timezone information is lost (such as lastModified in the Solr search core). I'll try out the change and see if it resolves the problem.

**Comment by mwoodiupui** [comment] 2023-06-21 12:03
@christian-scheible is right:  the problem is that a local date-time is going into the database as if it were "timestamp with time zone", which it is not.  `Instant` is just another type of local date-time, without zone information.  When it is subsequently cached in Solr, there is not enough information to convert it properly.

Probably we need a ZonedDateTime or the like, whose relationship to UTC is known, then the usual `java.time` gymnastics to convert that to a Date.  IIRC there are some examples in #8890.

**Comment by christian-scheible** [comment] 2023-06-22 08:22
@uofmsean: I didn't manually add the timestamp using SQL, but rather by modifying an item in the DSpace frontend. Therefore, all the date handling was done through DSpace code.

**Comment by uofmsean** [comment] 2023-06-22 15:59
@christian-scheible, just to confirm, do you have the local timezone set for PostgreSQL and have you also tried "oai import" with -Duser.timezone=??? just to be sure? FYI, we're on DSpace 7.5 and using Java 11 and PostgreSQL 13.

I'm not seeing the same problem any more in our environment after I applied the fix I outlined above, and we are in the America/Winnipeg timezone so we're currently -5 hours from UTC. Without the fix, the SimpleDateFormat string will use the local default timezone to format the time, and this gets lost when it is put in Solr because the SOLR_DATE_FORMAT assumes you are formatting as UTC.

**Comment by christian-scheible** [comment] 2023-06-26 11:21
Hi @uofmsean,

I have tried and applied your fix, which resolves the issue of items not getting indexed after a change. However, the date in item.lastmodified is still incorrect in my case. It currently shows: 2023-06-26T09:16:33.664Z, but it should be: 2023-06-26T11:16:33.664Z.

All time zones on our servers (Solr, DSpace, database) are set to Europe/Berlin.

**Comment by christian-scheible** [comment] 2023-06-27 06:36
@uofmsean yes, I removed my change before trying your solution.

**Comment by prynhart** [comment] 2023-07-25 01:22
Hi @uofmsean and/or @christian-scheible: Would it be possible to please provide the suggested source code fix (I'm assuming the file is ./app-dspace-backend-dspace-7.5/dspace-api/src/main/java/org/dspace/util/SolrUtils.java) ?

I've read the above, but unsure how to translate what has been written into code :).  Thanks, Patrick

**Comment by tdonohue** [comment] 2023-07-28 17:33
For anyone impacted by this bug, there's a PR created at #8984 by @uofmsean .   Additional testers welcome, as it'll help ensure this gets merged quickly!

**Comment by prynhart** [comment] 2023-07-31 03:30
Thanks @tdonohue for the comment and @uofmsean for the proposed PR.  I've tested the source code change and it's working well.  It resolves the issue for us 👍

**Closed** 2023-10-27 15:47 UTC
Labels: bug, backend: Solr, interface: OAI-PMH, help wanted
