### ISSUE TITLE
Item type repeats list 

### ISSUE THREAD

**Issue by alexahight** [DSpace/DSpace#2946] opened 2020-08-31 21:08 UTC
**Item type repeats list**
Testing in DSpace 7, uploading a test item, at "Item Type" there is a list of item types if one clicks on the arrow to the right of the entry box, but as one scrolls, the list repeats over and over.

**Comment by tdonohue** [comment] 2020-09-08 17:31
Closing as a duplicate of #482.  This is a known bug, tentatively scheduled for 7.0beta5

**Closed by tdonohue** 2020-09-08 17:31 UTC
Labels: bug, needs triage
