### ISSUE TITLE
Azure Active Directory (Shibboleth) user can change their password and login as local DSpace user using their new password

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/DSpace#7959] opened 2021-09-23 23:16 UTC
**Description of bug**
Issue is in DSpace7 (unknown if present in previous versions). The issue is on our UAT test instance (we are going live with DSpace7 in Dec 2021 and have not used DSpace before).
We successfully configured authentication with Azure Active Directory (AD) but one requirement of the university is not met, i.e. that AD users must not be able to change their password on DSpace. AD users **can** change their password in DSpace.
AD users can change their password in DSpace user management and later login using local user login page with email and new password. The "new" password is stored in DSpace user management and AD users can bypass AD authentication by logging in with "new" password.

1. Login with AD account
2. Go to profile and change & save new password
3. Logout and close browser
4. Open DSpace again and login as **local** user (local login in our case is visible by adding /login to end of URL) with new password. 
5. Login is successful - which means user bypassed AD authentication, which is not acceptable.

**Expected behavior**
AD users should not be able to change their password in DSpace.

**Comment by abollini** [comment] 2021-11-10 11:00
This requires changes on both the REST and Angular side.
On the REST side we need (8 hours)
- to implement a authorization feature to inform angular if password change is allowed or not
- protect the patch eperson to prevent update of the password if the password authentication is not supported
On the Angular side the profile page should use the new authorization feature to include or not the security panel. (2h)

Support for changing password on remote IdP is out-of-scope. We are interested in this task

**Comment by tdonohue** [comment] 2021-11-10 17:44
Thanks @abollini !  Will assign this back to both you and @atarix83, since it requires both frontend & backend changes.  As it's a relatively small ticket, I'll combine both into this ticket and add a 10 hour estimate.

**Comment by benbosman** [comment] 2021-11-19 08:19
@tdonohue This ticket was agreed to be assigned to Atmire yesterday
We would also want to adjust the solution so it better matches the DSpace 6 behavior and the expected behavior for people who have password login and shibboleth enabled.
Rather than simply preventing this when only shibboleth authentication is enabled, we'd want to also prevent this when shibboleth and password authentication are enabled, but the user authenticated using shibboleth.

This implies we'll need to keep track of how the user authenticated.
So we'll be storing in your authentication credential which authentication method you've used, and only allow edit password if the user did log in via password. I'm updating the estimate based on that solution as well

**Comment by tdonohue** [comment] 2021-11-19 17:54
@benbosman : I'd appreciate more information here on your estimate for this part...

> This implies we'll need to keep track of how the user authenticated.
So we'll be storing in your authentication credential which authentication method you've used, and only allow edit password if the user did log in via password. I'm updating the estimate based on that solution as well

I do agree this sounds like a worthwhile update. My assumption is the easiest route here might be to simply store your authentication method as part of your JWT auth token.  This information should likely "live" with the auth token itself, rather than trying to build anything more complex via the database or a new endpoint.  So, I'd like to understand if your extra 14 hours here is based on something more complex, or a similar design.

**Comment by benbosman** [comment] 2021-11-23 12:01
The solution here would indeed be to store it as part of the JWT auth token, and not the database or a new endpoint.
But that **can** have an impact on a rather large amount of code, to ensure the JWT auth token will know the current authentication method, and it can be retrieved (and there are sufficient tests to ensure this keeps working).

It can be less than the 24 hours, but I preferred a more careful estimate instead of running into a larger amount of work during the development.

**Comment by tdonohue** [comment] 2021-11-23 14:57
@benbosman : Thanks for the explanation. Please obviously try to get this under 24hrs if possible.  My hope is this won't be as difficult as it may seem, as storing in the JWT (even with new tests) shouldn't be as complex as storing it in database or elsewhere.  The JWT based code already has a large number of tests, so it should help ensure this new change doesn't effect other code.

**Comment by benbosman** [comment] 2021-12-07 09:24
@paulo-graca when they log in via their password, it's still possible
But as you requested in the implementation review, it can be made configurable to also support this for Shib if there's budget left

**Closed** 2022-01-04 16:08 UTC
Labels: bug, high priority, authentication: Shibboleth, e/24, help wanted
