### ISSUE TITLE
Curation task results are not included in the output file or standard out.

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8033] opened 2021-11-18 14:27 UTC
**Describe the bug**
When running a curation task via the DSpace 7.0 CLI, the output generated by the task process is only written to the dspace.log but not written to the output file or standard out.

**To Reproduce**
Easiest example is to run the NoOpCurationTask on both DSpace 6 and DSpace 7:

```
dspace curate -e admin -i 12345678/9 -t noop -v -r -
```

> -r filename | emit reporting to the named file.  '-r -' writes reporting to standard out.  If not specified, report is discarded silently.

**Expected behavior**
This command should write the Curation Task result string "No operation performed on 12345678/9" to standard out.

In DSpace 6 the output is:
```
Adding task: noop
Starting curation
Curating id: 12345678/9
No operation performed on 12345678/9
Ending curation. Elapsed time: 70
```

In DSpace 7 the output is:
```
The script has started
Adding task: noop
Starting curation
Curating id: 12345678/9
Ending curation. Elapsed time: 33
The script has completed
```

Of course, if you use another task than NoOpCurationTask, you can expect a more useful result string ;)

**Related work**
The same issue of missing results of curation task executions has been reported on the Angular-UI side:
[Curation task results are not included in the output file or process output #1322](https://github.com/DSpace/dspace-angular/issues/1322)

**Comment by tdonohue** [comment] 2021-12-03 20:33
I believe this is essentially a duplicate of https://github.com/DSpace/dspace-angular/issues/1322.  In v7, the same code drives the logging in both the outputfile & the CLI.  So, I'm pretty sure that when https://github.com/DSpace/dspace-angular/issues/1322 is fixed, this issue would also be fixed.

**Comment by tdonohue** [comment] 2022-01-21 20:33
Closing, this appears to be a duplicate as described above.

**Closed by tdonohue** 2022-01-21 20:33 UTC
Labels: bug, duplicate
