### ISSUE TITLE
Tomcat returns HTTP STATUS 404 on DSpace 7.3 and 7.4

### ISSUE THREAD

**Issue by lep-flp** [DSpace/DSpace#8519] opened 2022-10-13 17:30 UTC
**Describe the bug**
Tried running DSpace 7.3 and 7.4 on Jammy Jellyfish. However, tomcat9 returns HTTP STATUS 404 upon accessing localhost:8080/server. I did the same thing with DSpace 7.2.1, but tomcat was able to access the backend REST API. 

openJDK - 17.0.4
Maven - 3.8.6
Ant - 1.10.12
solr -8.11.2
db - post 13
solr - 8.11.2
tomcat - 9
OS - Jammy Jellyfish

**To Reproduce**
1. Download Dspace 7.3 or 7.4
2. Configure local.cfg
3. Run _mvn package_ and _ant fresh_install_
4. create server.xml and root.xml on $CATALINA_HOME/conf/Catalina/localhost to point to /DSPACE
5. Access http://localhost:8080/server
6. It shows HTTP STATUS 404 - Not found

**Expected behavior**
Rest API should be show just like in DSpace 7.2.1. However, tomcat returns HTTP STATUS 404.

**Comment by tdonohue** [comment] 2022-10-13 17:39
@lep-flp : A 404 error from Tomcat means that Tomcat didn't start up properly. You'd have to review your Tomcat & DSpace logs to see if an error was thrown that blocked the ability of DSpace to startup.  See our Troubleshooting guide for how to find that error & report it: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

I can verify that both DSpace 7.3 and 7.4 can run fine on Tomcat 9.  Chances are there's something in your configuration or setup which is resulting in a major startup failure.  Once you find the problem, if it doesn't make sense what is going on, please feel free to report the full error via our Support channels: https://wiki.lyrasis.org/display/DSPACE/Support  Someone there will try to help out.

Closing this as answered. It's not reproducible.

**Closed by tdonohue** 2022-10-13 17:39 UTC
Labels: bug, cannot reproduce, needs triage

**Comment by lep-flp** [comment] 2022-10-15 19:25
Ok. I have finally fixed it. The issue on my end was my solr cores were not being read by solr and so, tomcat cannot deploy /server properly.

**Comment by vimalibre** [comment] 2022-11-30 10:17
> @lep-flp : A 404 error from Tomcat means that Tomcat didn't start up properly. You'd have to review your Tomcat & DSpace logs to see if an error was thrown that blocked the ability of DSpace to startup. See our Troubleshooting guide for how to find that error & report it: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)
> 
> I can verify that both DSpace 7.3 and 7.4 can run fine on Tomcat 9 (I'm running 7.4 on Tomcat 9 locally today with no issues). Chances are there's something in your configuration or setup which is resulting in a major startup failure. Once you find the problem, if it doesn't make sense what is going on, please feel free to report the full error via our Support channels: https://wiki.lyrasis.org/display/DSPACE/Support Someone there will try to help out.
> 
> Closing this as answered. It's not reproducible.



> Ok. I have finally fixed it. The issue on my end was my solr cores were not being read by solr and so, tomcat cannot deploy /server properly.

I got the same error.
Please share me what you have done to solve the problem?

**Comment by anikwai** [comment] 2023-08-17 00:32
> > @lep-flp : A 404 error from Tomcat means that Tomcat didn't start up properly. You'd have to review your Tomcat & DSpace logs to see if an error was thrown that blocked the ability of DSpace to startup. See our Troubleshooting guide for how to find that error & report it: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)
> > I can verify that both DSpace 7.3 and 7.4 can run fine on Tomcat 9 (I'm running 7.4 on Tomcat 9 locally today with no issues). Chances are there's something in your configuration or setup which is resulting in a major startup failure. Once you find the problem, if it doesn't make sense what is going on, please feel free to report the full error via our Support channels: https://wiki.lyrasis.org/display/DSPACE/Support Someone there will try to help out.
> > Closing this as answered. It's not reproducible.
> 
> > Ok. I have finally fixed it. The issue on my end was my solr cores were not being read by solr and so, tomcat cannot deploy /server properly.
> 
> I got the same error. Please share me what you have done to solve the problem?

1.  This assumes your dspace installation is /opt/dspace-7 `cp -R  /opt/dspace-7/solr/* /var/solr/data`
2. Amend Permission `chown -R solr:solr /var/solr/data`
3. Restart both Solr (since I'm in/opt/solr/bin) I can do `./solr restart -force`
4. Restart Tomcat9 `systemctl restart tomcat9.service`

That is how I resolved the issue on my end.
