### ISSUE TITLE
In Date facet, start date option should adjust with slider

### ISSUE THREAD

**Issue by alawvt** [DSpace/DSpace#8418] opened 2022-07-21 21:36 UTC
**Describe the bug**
In the date facet, as one adjusts the date slider or enters the start and end dates, the options below adjust for the end date but not the start date.
Example
1. Start at https://demo7.dspace.org/search,
<img width="262" alt="DateFacet_start" src="https://user-images.githubusercontent.com/13037168/180316595-efd8baa4-56d0-42b8-9527-6ef1dccef6bf.png">

2. Pick Start=1997; End=2009, 
<img width="262" alt="DateFacet_step1" src="https://user-images.githubusercontent.com/13037168/180316674-192bf7fe-537e-468c-bb49-8900c5199b75.png">
The options adjust for the end date (2009) but not for the start date (which should be 1997 and not 1600).  

3. Select option,  "1600-1999 (88)," https://demo7.dspace.org/search?f.dateIssued.min=1997&f.dateIssued.max=2009. This URL does not match the option 1997-1999, but rather 1997-2009. This results in 
<img width="262" alt="DateFacet_step2" src="https://user-images.githubusercontent.com/13037168/180316894-10a7b536-0903-4ab9-b3d3-f2946ccce3e9.png">
which again lists the date range as 1600-1999 but this time with 476 items.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**
I think the correct behaviour should return either the entire range requested as one option or the range broken into reasonable options that match but don't exceed the requested date range.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2022-07-22 14:35
@alawvt : I think this might be a duplicate of https://github.com/DSpace/dspace-angular/issues/1723   We recently discovered these date facets don't work properly for any date *prior to 1950*.  

I'll link this ticket up to that one, as I *suspect* the same bug is behind both tickets so they might be solvable together.

**Closed** 2022-10-20 11:02 UTC
Labels: bug, component: Discovery, Estimate TBD, help wanted, usability
