### ISSUE TITLE
CLI item import error (SAF)

### ISSUE THREAD

**Issue by mspalti** [DSpace/DSpace#3163] opened 2021-02-24 22:33 UTC
**Describe the bug**
The DSPace CLI item import is throwing a Spring exception when I import SAF directories.  However I am able to run other tasks, like item exporting. 

The CLI `ItemImportServiceFactory.getInstance().getItemImportService()` method returns a NullPointerException. 

Exception: null
java.lang.NullPointerException
	at org.dspace.app.itemimport.ItemImportCLITool.main(ItemImportCLITool.java:302)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:272)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:128)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:93)

I added System.out.println to `DSpaceServiceManager.getServiceByName()` to see the error report on the command line:

Error creating bean with name 'itemImportServiceFactory': Unsatisfied dependency expressed through field 'itemImportService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.app.itemimport.ItemImportServiceImpl#0' defined in file [/Users/michaelspalti/dspace-tomcats/dspace7/config/spring/api/core-services.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dspace.app.itemimport.ItemImportServiceImpl]: Constructor threw exception; nested exception is java.lang.NullPointerException

The `ItemImportService` bean is an autowired property of the `ItemImportServiceFactoryImpl`.

**To Reproduce**
1. Attempt to import items using SAF: e.g.  ./bin/dspace import --add --eperson=mspalti@willamette.edu --collection=10177/2 --source=scene1926/batch_1 --mapfile=scene_1926

**Expected behavior**
Items should load successfully. I built my local DSpace from an earlier commit **793ac8c0d** the load was successful.

**Comment by tdonohue** [comment] 2021-02-24 22:36
I've been able to reproduce this myself.  Export works fine, but Import does not.  Looking around to see if I can figure out an obvious problem with the import script

**Comment by tdonohue** [comment] 2021-04-16 17:09
This issue still exists in Beta 5 (just verified).  @abollini , assigning to your team to investigate / estimate further.  Also labeling as `high priority` since this must be fixed in 7.0

**Comment by mspalti** [comment] 2021-04-17 22:15
@tdonohue , @abollini, this is a simple fix.  I was just preparing a PR when I saw the triage flag on the issue. I'll go ahead with the commit and you can evaluate.

**Comment by tdonohue** [comment] 2021-04-19 14:50
Thanks @mspalti !  We'll move along your PR & I'll reassign this ticket to you (since you created the PR).

**Closed** 2021-04-27 20:05 UTC
Labels: Estimate TBD, bug, high priority, interface: command-line, tools: import

**Comment by mwoodiupui** [comment] 2021-05-12 20:28
The NPE was caused by trying to dereference an @Autowired field in the initialization block, where the reference has not yet been set.  I recall several of these recently.  How can we get the word out among DSpace developers that injected references *cannot* be used in class initializers, instance initializers or constructors?
