### ISSUE TITLE
Search returns incorrect totalElements if size > totalElements

### ISSUE THREAD

**Issue by tlloydthwaites** [DSpace/DSpace#8105] opened 2022-01-10 05:01 UTC
**Describe the bug**
When calling /api/discover/search/objects, if supplying a page value greater than the total results, then totalElements is always 100.

**To Reproduce**
1. Call https://divinity.intersearch.com.au/divinityserver/api/discover/search/objects?dsoType=item&f.dateIssued=2015,equals&size=257
2. totalElements will be correct(257): `"page": {
                "number": 0,
                "size": 257,
                "totalPages": 1,
                "totalElements": 257
            },`
3. Change 'page' to 258: `"page": {
                "number": 0,
                "size": 258,
                "totalPages": 1,
                "totalElements": 100
            },`

**Expected behavior**
I presume totalElements should always reflect the actual number of available elements in the query result.

**Comment by tdonohue** [comment] 2022-05-09 16:47
@tlloydthwaites : I realize this ticket is a bit old, but wanted to note that I'm not able to reproduce this in the latest code, or on our demo site REST API at https://api7.dspace.org/

So, I think this bug has been resolved somewhere in the last few months.  Closing as fixed, but let us know if you find a way to reproduce this on our demo site.

**Closed by tdonohue** 2022-05-09 16:47 UTC
Labels: bug, needs triage

**Comment by tlloydthwaites** [comment] 2022-05-10 04:39
Thanks @tdonohue, I had trouble reproducing on demo as well, so it must be something at our end!
