### ISSUE TITLE
Curation tasks don't show any output/feedback in the interface

### ISSUE THREAD

**Issue by fribeiro-fccn** [DSpace/DSpace#8196] opened 2022-03-08 14:01 UTC
**Describe the bug**
Every curation task in backoffice don't gice any output to the user. Only states that the curation has started and has ended!

**To Reproduce**

1. Enter the backofiice and execute any of the curation tasks (NOP, metadata, links, doi)
2. Enter an handle
3. Execute the curation task
4. The output is blank.

See the example above:
![image](https://user-images.githubusercontent.com/65163266/157252467-30989df9-93b2-4c30-bd85-d10d90573265.png)

**Expected behavior**
should give som sort of information to the user who requested the taks. Example. If the chek links is selected what are the links that are ok and the ones that aren't

Greets
Fernando

**Comment by tdonohue** [comment] 2022-03-08 14:28
Closing, as this is a duplicate of https://github.com/DSpace/dspace-angular/issues/1322

**Closed by tdonohue** 2022-03-08 14:28 UTC
Labels: bug, duplicate, tools: curation-tasks
