### ISSUE TITLE
DSpace 6: Item move operation can accidentally delete items

### ISSUE THREAD

**Issue by hzafar** [DSpace/DSpace#8055] opened 2021-12-06 22:00 UTC
**Describe the bug**
When an item is moved from one collection to another, the back end does not validate the collections that the item is being moved from and to. Normally, this is not an issue because the admin UI will filter the appropriate collections for the user to choose from. However, there is an easily reproducible scenario where this results in the accidental deletion of the item and all of its bitstreams.

**To Reproduce**
1. Find an item, X, **belonging to a single collection**, Collection A, and move it through the Edit Item admin page to Collection B.
2. After the move completes successfully and you are taken back to the Edit Item page, refresh the page and agree to resubmit the form. (In practice, users may be working quickly and not notice what the form submission notice says; the consequences should not be as dire as an item being accidentally deleted.)
3. After the move request is processed the second time, the item becomes orphaned and all bitstreams for the item are deleted. 

This seems to happen because the item already belongs to Collection B after the first move, so the second time we attempt to move it from Collection A to Collection B, adding B to its collections has no effect. However, the logic in [CollectionServiceImpl](https://github.com/DSpace/DSpace/blob/97d0a1f12855b3451c77435591368c4c224b5138/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L646) erroneously determines that the item has now been orphaned, since it is only part of one collection when removeItem is called.

**Expected behavior**
Moving an item should be an idempotent operation. If the item already belongs to the collection it is being moved to, it should not become orphaned as a result of a move operation.

**Comment by tdonohue** [comment] 2022-01-21 20:12
@hzafar : Apologies for the delay in responding to this ticket, but I'm not able to reproduce this on our DSpace 7 demo site (or locally) at demo7.dspace.org. I had assumed that this was occurring in DSpace 7, but maybe you are reporting this for an older version of DSpace?

I attempted to reproduce this via the three steps you provided. However, during step 2, refreshing the page doesn't prompt me to resubmit the form (at least not on DSpace 7).  So, I cannot get the move to trigger twice in DSpace 7.

**Comment by hzafar** [comment] 2022-01-21 20:20
Oh, my apologies for not specifying -- this was happening in our DSpace 6 instance.

**Comment by tdonohue** [comment] 2022-01-21 22:58
@hzafar : Since this is v6, is this XMLUI or JSPUI?  We'd need the full details in this ticket for us to be able to replicate it.

As noted though, this seems to be fixed in v7.

**Comment by hzafar** [comment] 2022-01-24 15:08
Hi, it's JSPUI that we're using. Also, the fact that this is not occurring in v7 is great news as we're planning to upgrade this year. :)

I'd be happy to volunteer a PR myself if it's not urgently needed, as I probably won't have the time this week...

**Comment by tdonohue** [comment] 2022-01-24 15:18
@hzafar : A PR would be welcome, as most of our developers are currently working on 7.x, which means there's less activity on 6.x at this time.  So, you'd likely get to a PR before anyone else would.

**Comment by tdonohue** [comment] 2022-02-15 15:46
Closing, fixed by #8171 (in 6.x) and #8163 (in 7.x)

**Closed by tdonohue** 2022-02-15 15:46 UTC
Labels: bug, interface: JSPUI, Estimate TBD, help wanted
