### ISSUE TITLE
Batch update returned unexpected row count from update

### ISSUE THREAD

**Issue by dinshi17** [DSpace/DSpace#7932] opened 2021-09-07 10:30 UTC
How to fix the "batch update returned unexpected row count from update" error at Dspace.

**Comment by tdonohue** [comment] 2021-09-07 13:55
@dinshi17 :  We'd need more information on how to reproduce this error, along with any errors that may appear in the logs.  See https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error  You also have not provided the version of DSpace you are using, etc.

Without more information about how you encountered this error & the version of DSpace you are using, this is not possible to solve.

**Comment by dinshi17** [comment] 2021-09-08 06:29
Hi, Thanks for the quick response, We use Dspace 6, and this happened while we were uploading papers in to a folder. 
It will display "Batch update returned unexpected row count from update"
It is not possible to erase some folders. Actually we are revamping the structure of the dspace these days.

**Comment by tdonohue** [comment] 2021-09-08 13:49
Hi @dinshi17 : When reporting a bug, we need you to provide more information about how to reproduce the bug. If we cannot reproduce the bug, we won't be able to easily fix it.  Unfortunately, the information you've provided is still too vague for us to reproduce this bug.  A few questions include:

* What version of DSpace 6 are you using?  6.1? 6.2? 6.3?
* What exact command were you running when the error occurred?
* What was the error stacktrace associated with this error message (at that often includes important information like line numbers in the code, etc, which let us track down the error).  Again, see https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error for information on finding the entire error stacktrace.
* Were you ever able to workaround the error or does it occur on every batch import/update?

If you can provide us with additional details that'd help us try and reproduce the issue

**Comment by tdonohue** [comment] 2021-09-24 15:23
Closing as this is missing step-by-step information on how to reproduce in 6.x.  I've not been able to figure out where this might occur & it's possible it might have been a configuration issue or similar.  If further info is provided this can always be reopened at a later date.

**Closed by tdonohue** 2021-09-24 15:23 UTC
Labels: bug, needs triage
