### ISSUE TITLE
CC licence step does not work

### ISSUE THREAD

**Issue by Simone-Ramundi** [DSpace/DSpace#9603] opened 2024-05-21 15:29 UTC
**Describe the bug**
The bug occurs in DSpace 8 version when configuring CC licence step as mandatory field and not licence is selected, no submission's error is shown allowing the user's submission deposit.
 
**To Reproduce**
1. Set mandatory property as ‘true’ inside the following path: dspace/config/item-submission.xml
 
**Expected behavior**
If user forgets to select cc licence or does not select any of the available ones, an error must be shown as it happens for mandatory section 'Deposit licence'.

**Comment by tdonohue** [comment] 2024-05-22 19:21
@hutattedonmyarm : is correct.  This is a not a bug, but rather is a request for a new feature. Currently the CC License is *always optional*.  However, this ticket is asking for a new feature/improvement to allow a way to make it required.

I've also discovered this ticket is a duplicate of https://github.com/DSpace/dspace-angular/issues/2161

Closing this ticket in favor of https://github.com/DSpace/dspace-angular/issues/2161  I've linked @hutattedonmyarm 's comment into that ticket.

**Closed by tdonohue** 2024-05-22 19:21 UTC
Labels: bug, needs triage
